### ISSUE TITLE
Android latest appcompact-v7 support

### ISSUE THREAD

**Issue by trevorwang** [msintuneappsdk/ms-intune-app-sdk-android#1]
I met this kind of issue when I integrating with intune sdk.

```
  Process: com.bhpb.travel, PID: 17348
                                                                 java.lang.AbstractMethodError: abstract method "boolean android.support.v7.app.AppCompatDelegate.applyDayNight()"
                                                                     at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:74)
                                                                     at com.microsoft.intune.mam.client.support.v7.app.MAMAppCompatActivityBase.onCreateReal(MAMAppCompatActivityBase.java:80)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(InterProxy.java:70)
                                                                     at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                                     at $Proxy9.onCreateReal(Unknown Source)
                                                                     at com.microsoft.intune.mam.client.app.ActivityBehaviorImpl.onMAMCreate(ActivityBehaviorImpl.java:445)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(InterProxy.java:70)
                                                                     at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                                     at $Proxy8.onMAMCreate(Unknown Source)
                                                                     at com.microsoft.intune.mam.client.support.v7.app.MAMAppCompatActivityBase.onMAMCreate(MAMAppCompatActivityBase.java:72)
```

It seems that  `MSMAMAppCompatDelegateWrapper` class doesn't implement `applyDayNight` method.

When will this SDK support the Android N release? 

> The Intune App SDK is a compiled Android project. As a result, it is largely agnostic to the version of Android the app uses for its minimum or target API versions. The SDK supports Android API 14 (Android 4.0+) to Android 24.

**Comment by msintuneappsdk** [comment]
@trevorwang The next release of the SDK will have Android N support.

**Comment by trevorwang** [comment]
@msintuneappsdk  Is there a timeline? I am currently working on a app using this SDK. And we need the latest support package (24.x.x)

**Comment by msintuneappsdk** [comment]
@trevorwang I do not have a timeline yet for the public SDK release. We may be able to give you a private build. What company do you work for? Is your app an internal line-of-business app for your company? Or will it be publicly released to an app store?

**Comment by trevorwang** [comment]
It's great if I can get the private build. All my apps are internal app and will be deployed on our Intune env.

**Comment by msintuneappsdk** [comment]
Hi @trevorwang we should be releasing by the end of the month, does that timeline work for you?

**Comment by trevorwang** [comment]
Yes. It makes sense if it's released on time.

**Comment by trevorwang** [comment]
@msintuneappsdk  I have noticed that iOS version and Android wrapping tools has beed updated. When will release this SDK to be upgraded?

**Comment by trevorwang** [comment]
@msintuneappsdk  What's the plan to support  v7 version of 26

**Comment by msintuneappsdk** [comment]
Hi Trevor, thanks for reaching out. We should be releasing some Android API 26 support by the end of the month.

**Comment by trevorwang** [comment]
@msintuneappsdk Do you have any progress of API 26 support?

**Comment by meghandaly** [comment]
The current SDK supports Android API 19 (Android 4.4+) through Android API 28 (Android 9.0).
