### ISSUE TITLE
When I click the next in the MAMStartupActivity the comes the crash  java.lang.ClassNotFoundException: com.microsoft.intune.mam.client.app.startup.ConditionalLaunchGetAccessFragment

### ISSUE THREAD

**Issue by Nash123-start** [msintuneappsdk/ms-intune-app-sdk-android#101]
java.lang.RuntimeException: Unable to destroy activity {com.ringcentral.intune/com.microsoft.intune.mam.client.app.startup.MAMStartupActivity}: java.lang.ClassNotFoundException: com.microsoft.intune.mam.client.app.startup.ConditionalLaunchGetAccessFragment
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5456)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5493)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8154)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: java.lang.ClassNotFoundException: com.microsoft.intune.mam.client.app.startup.ConditionalLaunchGetAccessFragment
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at leakcanary.AppWatcher$objectWatcher$1.expectWeaklyReachable(AppWatcher.kt:76)
        at leakcanary.internal.AndroidOFragmentDestroyWatcher$fragmentLifecycleCallbacks$1.onFragmentDestroyed(AndroidOFragmentDestroyWatcher.kt:49)
        at android.app.FragmentManagerImpl.dispatchOnFragmentDestroyed(FragmentManager.java:3447)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1457)
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
        at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3032)
        at android.app.FragmentController.dispatchDestroy(FragmentController.java:250)
        at android.app.Activity.performDestroy(Activity.java:8224)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1342)

**Comment by Nash123-start** [comment]
![1811646095532_ pic](https://user-images.githubusercontent.com/97157482/156083337-b638bba6-dded-44d7-91ad-06a23586b691.jpg)
After I integrated the InTune SDK and opened the app, this page appeared, and when I clicked Next, it crashed

Could you please tell me what specific information you need to provide

This issue is urgent and looking forward to your reply

**Comment by Nash123-start** [comment]
Thank you for your reply

**Comment by bannus** [comment]
Hi @Nash123-start, when you created an issue, the following template should have been auto-populated -- please fill this out. For your case, we will likely need Company Portal logs. Could you follow the directions at https://docs.microsoft.com/en-us/mem/intune/user-help/send-logs-to-microsoft-android to upload logs. Please relay the incident ID here and we can take a look.

**Describe the bug:**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior:**
A clear and concise description of what you expected to happen. 

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is experiencing an issue during build, do you have error logs?
- If your app is experiencing an issue post build, do you have app logs for the crash itself?

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated?
- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**
Add any other context about the problem here.

**Comment by Nash123-start** [comment]
This crash is due to the leakcanery has fixed it
