### ISSUE TITLE
Getting crashes on com.microsoft.identity.common.internal.broker.BrokerActivity.onMAMCreate

### ISSUE THREAD

**Issue by sandeepbhatia4922** [msintuneappsdk/ms-intune-app-sdk-android#103]
App is crashing at BrokerActivity.java line 61

I am getting logs

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.condecosoftware.condeco/com.microsoft.identity.common.internal.broker.BrokerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6718)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
       
  Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference
       at com.microsoft.identity.common.internal.broker.BrokerActivity.onMAMCreate(BrokerActivity.java:61)
       at com.microsoft.intune.mam.client.app.offline.OfflineActivityBehavior.onCreate(OfflineActivityBehavior.java:90)
       at com.microsoft.intune.mam.client.app.MAMActivity.onCreate(MAMActivity.java:77)
       at android.app.Activity.performCreate(Activity.java:7144)
       at android.app.Activity.performCreate(Activity.java:7135)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6718)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by boyzhang-msft** [comment]
Hi @sandeepbhatia4922 ,

Thanks for the stack trace. This **method** com.microsoft.intune.mam.client.app.offline.**OfflineActivityBehavior.onCreate(OfflineActivityBehavior.java:90**)

is calling the `onCreate ` method in your `BrokerActivity`. So the crash should be caused by something in your `onCreate` method.

To confirm, could you remove the MAM integration, and see if the crash repros? If not, could you provide a minimum repro app that I can test on my end?

Thank you,
Boyu

**Comment by meghandaly** [comment]
@sandeepbhatia4922 Can you comment on whether you are still experiencing this issue? If do, can you provide us with the information Boyu requested? If not, can you comment on what resolved the issue?

**Comment by sandeepbhatia4922** [comment]
@meghandaly I have removed the MAM integration but unable to repro crash. I have reported this crash from firebase crashlytics only once. On my side I never saw it. So unable to repro it

**Comment by meghandaly** [comment]
@sandeepbhatia4922 Understood. Given the inability to reproduce and the limited scope (1) of the crash we do not have enough information to act at this time.

If that changes in the future, please reactivate with additional context.
