### ISSUE TITLE
getting crash on com.microsoft.intune.mam.client.app.resolver.MAMResolverActivity.onMAMCreate

### ISSUE THREAD

**Issue by sandeepbhatia4922** [msintuneappsdk/ms-intune-app-sdk-android#104]
app crashes at com.microsoft.intune.mam.client.app.resolver.MAMResolverActivity.onMAMCreate
MAMResolverActivity.java line 20
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.condecosoftware.condeco/com.microsoft.intune.mam.client.app.resolver.MAMResolverActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.microsoft.intune.mam.client.app.resolver.MAMResolverUIBehavior.onBeforeActivityCreate(android.app.Activity, android.os.Bundle)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6124)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:890)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:780)

Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void com.microsoft.intune.mam.client.app.resolver.MAMResolverUIBehavior.onBeforeActivityCreate(android.app.Activity, android.os.Bundle)' on a null object reference
       at com.microsoft.intune.mam.client.app.resolver.MAMResolverActivity.onMAMCreate(MAMResolverActivity.java:20)
       at com.microsoft.intune.mam.client.app.offline.OfflineActivityBehavior.onCreate(OfflineActivityBehavior.java:90)
       at com.microsoft.intune.mam.client.app.MAMActivity.onCreate(MAMActivity.java:77)
       at android.app.Activity.performCreate(Activity.java:6699)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6124)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:890)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:780)
```

**Comment by boyzhang-msft** [comment]
Hi @sandeepbhatia4922 ,

The stack trace looks a little mysterious. The `OfflineActivityBehavior` indicates that you are in offline mode (i.e. the Company Portal app or the TestAgent app is not on device), but I don't think MAM would bring up `MAMResolverActivity` in offline mode, and you can only get an instance of `MAMResolverUIBehavior` in online mode (i.e. the Company Portal App or the TestAgent app is on device).

Could you share a minimum repro app and the repro steps for further investigation?

Thank you,
Boyu

**Comment by sandeepbhatia4922** [comment]
hi @boyzhang-msft  I have registered MAMAuthenticationCallback inside onCreate() of Application class

` OfflineComponents.initialize(applicationContext)
        val mgr = MAMComponents.get(MAMEnrollmentManager::class.java)
        mgr?.registerAuthenticationCallback(AuthenticationCallback(applicationContext))`

and the manifest file as
`<application
        android:allowBackup="false"
        android:fullBackupContent="false"
        android:backupAgent="com.microsoft.intune.mam.client.app.backup.MAMDefaultBackupAgent"`>

**Comment by meghandaly** [comment]
@sandeepbhatia4922 Are you still experiencing this issue?

**Comment by sandeepbhatia4922** [comment]
@meghandaly I have reported this crash from firebase crashlytics only once. 
This happens with device :-
**Device** 
Brand: samsung
Model:Galaxy Tab A
Orientation: Landscape
RAM free: 3.1 GB
Disk free: 14.03 GB
**Operating System**
Version:Android 7.1.2
Orientation: Landscape
Rooted:Yes

**Comment by meghandaly** [comment]
@sandeepbhatia4922 Given the limited scope (1) and information associated with this crash, we do not have enough information to mount an investigation at this time. Should that change in the future, please reactivate with additional context.
