### ISSUE TITLE
App crash due to AgentIpcException

### ISSUE THREAD

**Issue by sandeepbhatia4922** [msintuneappsdk/ms-intune-app-sdk-android#105]
app is crashing due to Fatal Exception: com.microsoft.intune.mam.client.ipc.exceptions.AgentIpcException

I have got crash report from firebase crashlytics. Kindly check the logs and do needful

```
Fatal Exception: com.microsoft.intune.mam.client.ipc.exceptions.AgentIpcException: Android threw IllegalArgumentException. Agent flags: 0doze: false; app inactive: false; agent inactive: false; device interactive: false; power save: false; agent disabled: false; provider disabled: false. Method invoked: methodName: onMAMAppInstall; returnType: void  at com.microsoft.intune.mam.client.ipc.ContentProviderEndpointProxy$EndpointProxyInvocationHandler.doAgentIpc(ContentProviderEndpointProxy.java:184) at com.microsoft.intune.mam.client.ipc.ContentProviderEndpointProxy$EndpointProxyInvocationHandler.lambda$invoke$0$ContentProviderEndpointProxy$EndpointProxyInvocationHandler(ContentProviderEndpointProxy.java:107) at com.microsoft.intune.mam.client.ipc.-$$Lambda$ContentProviderEndpointProxy$EndpointProxyInvocationHandler$cVECf9axIoLRDqJ_Y6oDZqcwBXs.call(-.java:10)
       at com.microsoft.intune.mam.client.identity.IdentityCallable.call(IdentityCallable.java:38)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:929)
```

**Comment by boyzhang-msft** [comment]
Thanks for the information, and this is a known issue on our side. We have an internal bug tracking it and we have been working on it incrementally. Unfortunately, we don't have a local repro either. Please keep an eye out for any increasing trend and let us know!

**Comment by Nash123-start** [comment]
When will this bug be fixed

**Comment by bannus** [comment]
@Nash123-start No ETA at this time. If you have any information about incidence rate or product impact that could impact our prioritization, please share here.

**Comment by Durzan666** [comment]
Are there any updates on this issue?

**Comment by Archit-Pikle** [comment]
Hi @Durzan666, we don't have an ETA at this time

**Comment by sandeepbhatia4922** [comment]
@bannus @meghandaly  When will this be fixed. Any update plaese?

**Comment by shashank-ADOBE** [comment]
Facing the same issue with our Acrobat Reader application, please update on the timelines for the fix.

**Comment by MAgungHKM** [comment]
One of our user is facing the same issue on his **Samsung Galaxy S21** with **Android 14**. But, the crash issue doesn't seem to happen on our team's **Samsung Galaxy S23,** also with **Android 14**.

**Comment by yinkang-huang** [comment]
Hi team, this issue has been open for over **three years** and still impacts app functionality. Could you please prioritise a fix or provide a clear workaround?
