### ISSUE TITLE
Crash observed in OMADMTelemetry.java at line 90 due to "Fatal Exception: java.lang.RuntimeException"

### ISSUE THREAD

**Issue by naquee-rizwan** [msintuneappsdk/ms-intune-app-sdk-android#126]
**Describe the bug:**
App is crashing as soon as it is getting launched. This crash event happened in the first second of the user’s session.

**To Reproduce**
App is crashing as soon as it is launched.

**Expected behavior:**
App should not crash and users should have a seamless experience using application.

**Screenshots and logs:**
```
Fatal Exception: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1043580 bytes
       at android.app.ContextImpl.sendBroadcast(ContextImpl.java:975)
       at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:437)
       at com.microsoft.intune.omadm.diagnostics.domain.OMADMTelemetry.sendMAMTelemetryIntent(OMADMTelemetry.java:90)
       at com.microsoft.intune.omadm.diagnostics.domain.OMADMTelemetry.sendMAMTelemetryEvent(OMADMTelemetry.java:68)
       at com.microsoft.omadm.logging.MAMTelemetryLogger.logEvent(MAMTelemetryLogger.java:56)
       at com.microsoft.omadm.logging.MAMTelemetryLogger.logMAMError(MAMTelemetryLogger.java:123)
       at com.microsoft.omadm.apppolicy.MDMAppPolicyEndpoint.reportFatalError(MDMAppPolicyEndpoint.java:871)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.microsoft.intune.mam.client.ipc.AbstractAppPolicyContentProvider.call(AbstractAppPolicyContentProvider.java:162)
       at android.content.ContentProvider$Transport.call(ContentProvider.java:403)
       at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:272)
       at android.os.Binder.execTransact(Binder.java:697)
Caused by android.os.TransactionTooLargeException: data parcel size 1043580 bytes
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:764)
       at android.app.IActivityManager$Stub$Proxy.broadcastIntent(IActivityManager.java:4490)
       at android.app.ContextImpl.sendBroadcast(ContextImpl.java:970)
       at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:437)
       at com.microsoft.intune.omadm.diagnostics.domain.OMADMTelemetry.sendMAMTelemetryIntent(OMADMTelemetry.java:90)
       at com.microsoft.intune.omadm.diagnostics.domain.OMADMTelemetry.sendMAMTelemetryEvent(OMADMTelemetry.java:68)
       at com.microsoft.omadm.logging.MAMTelemetryLogger.logEvent(MAMTelemetryLogger.java:56)
       at com.microsoft.omadm.logging.MAMTelemetryLogger.logMAMError(MAMTelemetryLogger.java:123)
       at com.microsoft.omadm.apppolicy.MDMAppPolicyEndpoint.reportFatalError(MDMAppPolicyEndpoint.java:871)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.microsoft.intune.mam.client.ipc.AbstractAppPolicyContentProvider.call(AbstractAppPolicyContentProvider.java:162)
       at android.content.ContentProvider$Transport.call(ContentProvider.java:403)
       at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:272)
       at android.os.Binder.execTransact(Binder.java:697)
```

**Smartphone:**
 - Device: Sonimtech XP8
 - OS: 8.1.0

**Intune App SDK for Android:**
- What version of the Intune SDK are you using? Are you using the latest version?
          Version used - 8.3.0
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
           Native Android Application using Kotlin and Java.
- For errors during build, does the app build without Intune SDK integration?
            Not Applicable
- For errors post build, does the app launch without being Intune SDK integrated?
             Crash for this device is observed in this case only pointing to Intune SDK. No other crashes are logged for this device.
- Who is the customer?
             End Users
- Do you see a trend with it only being reproduced on a specific device?
              Crash is observed only for the mentioned device

**Additional context:**

**Comment by mcsimons** [comment]
Thanks for the report. We are internally tracking this bug with #15224562.
