### ISSUE TITLE
ANR when start a new activity

### ISSUE THREAD

**Issue by Nash123-start** [msintuneappsdk/ms-intune-app-sdk-android#128]
**Describe the bug:**
App Anr when start a activity.

**To Reproduce**
Start a new Activity (Once)

**Expected behavior:**
Should not Anr

**Screenshots and logs:**

"Intune MAM file logger" prio=5 tid=16 Waiting
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x144c05e8 self=0x7bf0042820
  | sysTid=17360 nice=0 cgrp=default sched=0/0 handle=0x7a0d1e8cc0
  | state=S schedstat=( 66007775 8371151 265 ) utm=3 stm=2 core=4 HZ=100
  | stack=0x7a0d0e5000-0x7a0d0e7000 stackSize=1043KB
  | held mutexes=
  at sun.misc.Unsafe.park(Native method)
  - waiting on an unknown object
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
  at com.microsoft.intune.mam.log.ThreadedFileHandler$PublishRunner.run(:78)

"Intune MAM enrollment retry" prio=5 tid=17 TimedWaiting
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x144c09f0 self=0x7bf0045fc0
  | sysTid=17361 nice=0 cgrp=default sched=0/0 handle=0x7a0c0decc0
  | state=S schedstat=( 689272 0 5 ) utm=0 stm=0 core=5 HZ=100
  | stack=0x7a0bfdb000-0x7a0bfdd000 stackSize=1043KB
  | held mutexes=
  at java.lang.Object.wait(Native method)
  - waiting on <0x00757fe8> (a android.os.ConditionVariable)
  at java.lang.Object.wait(Object.java:442)
  at android.os.ConditionVariable.block(ConditionVariable.java:128)
  - locked <0x00757fe8> (a android.os.ConditionVariable)
  at com.microsoft.intune.mam.policy.MAMWETaskQueue.getDueTasks(:91)
  at com.microsoft.intune.mam.policy.MAMWERetryScheduler$TaskRunner.run(:116)
  at java.lang.Thread.run(Thread.java:923)

"queued-work-looper" prio=5 tid=18 Native
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x144c0c80 self=0x7bf00443f0
  | sysTid=17363 nice=-2 cgrp=default sched=0/0 handle=0x7a0afd4cc0
  | state=S schedstat=( 84993342 8008697 241 ) utm=4 stm=3 core=7 HZ=100
  | stack=0x7a0aed1000-0x7a0aed3000 stackSize=1043KB
  | held mutexes=
  native: #00 pc 000000000009bf38  /apex/com.android.runtime/lib64/bionic/libc.so (__epoll_pwait+8)
  native: #01 pc 0000000000019ad0  /system/lib64/libutils.so (android::Looper::pollInner(int)+184)
  native: #02 pc 00000000000199b0  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112)
  native: #03 pc 0000000000110f80  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
  at android.os.MessageQueue.nativePollOnce(Native method)
  at android.os.MessageQueue.next(MessageQueue.java:335)
  at android.os.Looper.loop(Looper.java:183)
  at android.os.HandlerThread.run(HandlerThread.java:67)

"Intune MAM background-0" prio=5 tid=19 TimedWaiting
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x144c0d60 self=0x7bf004cf00
  | sysTid=17364 nice=0 cgrp=default sched=0/0 handle=0x7a09ecacc0
  | state=S schedstat=( 1056409 8802 9 ) utm=0 stm=0 core=6 HZ=100
  | stack=0x7a09dc7000-0x7a09dc9000 stackSize=1043KB
  | held mutexes=
  at sun.misc.Unsafe.park(Native method)
  - waiting on an unknown object
  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
  at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:461)
  at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
  at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  at java.lang.Thread.run(Thread.java:923)

**Smartphone (please complete the following information):**
 - Device: Pixel 3xl
 - OS: Android 11

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
  sdk: 8.6.1 msl lib:3.0.2
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
 Native android use java and kotlin
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated?
 Yes
- Who is the customer?
end use
- Do you see a trend with it only being reproduced on a specific device?
 Just produce once

**Additional context:**
There is the app log:
[bugreport-crosshatch-RQ2A.210305.006-2022-08-05-14-14-01.zip](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/files/9287394/bugreport-crosshatch-RQ2A.210305.006-2022-08-05-14-14-01.zip)

**Comment by mcsimons** [comment]
Hello, thanks for the report. 
Can you confirm if you are seeing this on only on one device or are you seeing a larger pattern of this?
Also, can you confirm if this has ever worked as expected?

**Comment by Nash123-start** [comment]
This ANR Just produce once

**Comment by joakley-msft** [comment]
While the ANR does show some threads containing waiting Intune code, this is expected. The main/UI thread does not appear to be waiting on Intune code.  Without a clear indication that Intune is triggering the ANR or steps to reproduce, I'm closing this. Please feel free to reactivate if I've missed something actionable.
