### ISSUE TITLE
App crash when App launch

### ISSUE THREAD

**Issue by Nash123-start** [msintuneappsdk/ms-intune-app-sdk-android#129]
escribe the bug:
App crash once when launch app 

To Reproduce
App is crashing as soon as it is launched.

Expected behavior:
App should not crash

Screenshots and logs:
Fatal Exception: java.lang.IllegalArgumentException: activity
       at com.microsoft.aad.adal.AuthenticationContext.wrapActivity(AuthenticationContext.java:1245)
       at com.microsoft.aad.adal.AuthenticationContext.acquireToken(AuthenticationContext.java:431)
       at com.microsoft.intune.mam.client.app.startup.auth.adal.ADALUserAuthentication.makeAuthCall(ADALUserAuthentication.java:250)
       at com.microsoft.intune.mam.client.app.startup.auth.adal.ADALUserAuthentication.startAuthentication(ADALUserAuthentication.java:240)
       at com.microsoft.intune.mam.client.app.startup.auth.adal.ADALUserAuthentication.startAuthenticationForMAM(ADALUserAuthentication.java:194)
       at com.microsoft.intune.mam.client.app.startup.auth.adal.ADALUserAuthentication.startAuthenticationForMAM(ADALUserAuthentication.java:174)
       at com.microsoft.intune.mam.client.app.startup.ConditionalLaunchFragmentBase.startAuthentication(ConditionalLaunchFragmentBase.java:728)
       at com.microsoft.intune.mam.client.app.startup.ConditionalLaunchAuthenticationFragment.startAuthentication(ConditionalLaunchAuthenticationFragment.java:1058)
       at com.microsoft.intune.mam.client.app.startup.ConditionalLaunchAuthenticationFragment.onRequiresAuthentication(ConditionalLaunchAuthenticationFragment.java:1016)
       at com.microsoft.intune.mam.client.app.startup.ConditionalLaunchAuthenticationFragment.retryAuth(ConditionalLaunchAuthenticationFragment.java:1053)
       at com.microsoft.intune.mam.client.app.startup.StartupFragmentBase.lambda$showRestartAuthDialog$0$StartupFragmentBase(StartupFragmentBase.java:86)
       at com.microsoft.intune.mam.client.app.startup.-$$Lambda$StartupFragmentBase$0Dnd9ML93762bgaRBINF-cf_1t8.onClick(-.java:2)
       at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:175)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7898)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

Smartphone (please complete the following information):

Device:Pixel 6
OS: Android 13
Intune App SDK for Android (please complete the following information):

What version of the Intune SDK are you using? Are you using the latest version?
Version used - 8.6.1 msal version 3.0.2
What platform is your app based in (Java, Xamarin based, Cordova, etc)?
Native Android Application using Kotlin and Java.
For errors during build, does the app build without Intune SDK integration?
For errors post build, does the app launch without being Intune SDK integrated?
Crash for this device is observed in this case only pointing to Intune SDK. No other crashes are logged for this device.
Who is the customer?
end user
Do you see a trend with it only being reproduced on a specific device?
Just crash once
Additional context:

**Comment by meghandaly** [comment]
@Nash123-start Please refer to the [Android versions](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#android-versions) requirements for integrating the Android MAM SDK. The highest Android OS version supported, at this time, is Android 12.

Additionally, the MAM team does not have the bandwidth to review every crash stack you may observe for your app. Please investigate further and open an issue if there is a definite pattern that can be attributed to MAM, or you suspect there may be. A single crash for a single user, does not meet that bar.
