### ISSUE TITLE
Android 13 crashes trying to get PackageInfo

### ISSUE THREAD

**Issue by lukaszciastko** [msintuneappsdk/ms-intune-app-sdk-android#136]
When running the following code on Android 13 with Intone 9.0.0 (Java/Kotlin):

```
        final PackageManager pm = getContext().getPackageManager();

        if (android.os.Build.VERSION.SDK_INT >= 33) {
            try {
                final PackageInfo info = pm.getPackageInfo(getContext().getPackageName(), PackageManager.PackageInfoFlags.of(PackageManager.GET_PERMISSIONS));
            } catch (PackageManager.NameNotFoundException e) {
                e.printStackTrace();
            }
        }
```

the app crashes with the following exception:

```
    java.lang.ClassCastException: Cannot cast com.microsoft.intune.mam.client.content.pm.OfflinePackageManagementBehavior to com.microsoft.intune.mam.client.content.pm.PackageManagementBehaviorTiramisu
        at java.lang.Class.cast(Class.java:2479)
        at com.microsoft.intune.mam.client.app.offline.OfflineComponents.get(OfflineComponents.java:351)
        at com.microsoft.intune.mam.client.app.MAMComponents.get(MAMComponents.java:646)
        at com.microsoft.intune.mam.client.app.-$$Lambda$JwjJSG2gOGv_Wb5mWx4DHyvzeFY.get(Unknown Source:0)
        at com.microsoft.intune.mam.client.InterfaceComponentsAccess.get(InterfaceComponentsAccess.java:30)
        at com.microsoft.intune.mam.client.CachedBehaviorProvider.getComponent(CachedBehaviorProvider.java:42)
        at com.microsoft.intune.mam.client.CachedBehaviorProvider.get(CachedBehaviorProvider.java:33)
        at com.microsoft.intune.mam.client.content.pm.MAMPackageManagement.getBehaviorTiramisu(MAMPackageManagement.java:637)
        at com.microsoft.intune.mam.client.content.pm.MAMPackageManagement.getPackageInfo(MAMPackageManagement.java:319)
```

**Comment by bannus** [comment]
Hi @lukaszciastko, thanks for the report. We are tracking this issue internally (bug 15572424).

**Comment by msft-cofitz** [comment]
@lukaszciastko [9.0.1](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/releases/tag/9.0.1) contains a fix for this issue. Please let us know if you continue to face the crash after updating.
