### ISSUE TITLE
intune sdk start Activity is error

### ISSUE THREAD

**Issue by yaxin3690** [msintuneappsdk/ms-intune-app-sdk-android#137]
Intent intent = new Intent(MainActivity.this, MainAppActivity.class);
                intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                startActivity(intent);

MainAppActivity.java
        WebView webView = findViewById(R.id.proc_text);
        webView.loadUrl("https://www.google.com.hk/");

16:40:57.271  5095-5123  nxin.intunetes                  I  Background concurrent copying GC freed 887619(65MB) AllocSpace objects, 2(13MB) LOS objects, 14% free, 139MB/163MB, paused 281us total 166.086ms
16:40:57.888  5095-5422  hwschromium-3139                I  [INFO:host_resolver_manager.cc(4399)] DOH-Fallback donn't probe secure dns since we donn't have secure dns fallback servers
16:40:58.005  5095-5165  JavaBinder                      E  !!! FAILED BINDER TRANSACTION !!!  (parcel size = 18904324)
16:40:58.005  5095-5165  ContentResolver                 W  RemoteException: provider.call
16:40:58.013  5095-5165  ntProviderEndpointProxy         W  Unable to invoke Agent content provider, waking and retrying.
                                                            com.microsoft.intune.mam.client.ipc.exceptions.AgentInterruptedException: After calling reportFatalError we received a null or empty bundle as a return. Agent could have been killed mid-transaction or the binder crashed. Agent flags: 0doze: false; app inactive: false; agent inactive: false; device interactive: true; power save: false; agent disabled: false; provider disabled: false
                                                            	at com.microsoft.intune.mam.client.ipc.BundleMarshal.unmarshalOne(:142)
                                                            	at com.microsoft.intune.mam.client.ipc.ContentProviderEndpointProxy$EndpointProxyInvocationHandler.makeContentProviderCall(:365)
                                                            	at com.microsoft.intune.mam.client.ipc.ContentProviderEndpointProxy$EndpointProxyInvocationHandler.doAgentIpc(:162)
                                                            	at com.microsoft.intune.mam.client.ipc.ContentProviderEndpointProxy$EndpointProxyInvocationHandler.lambda$invoke$0$ContentProviderEndpointProxy$EndpointProxyInvocationHandler(:107)
                                                            	at com.microsoft.intune.mam.client.ipc.-$$Lambda$ContentProviderEndpointProxy$EndpointProxyInvocationHandler$cVECf9axIoLRDqJ_Y6oDZqcwBXs.call(Unknown Source:10)
                                                            	at com.microsoft.intune.mam.client.identity.IdentityCallable.call(:38)
                                                            	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                            	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
                                                            	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
                                                            	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                            	at java.lang.Thread.run(Thread.java:784)
16:40:58.049  5095-5165  JavaBinder                      E  !!! FAILED BINDER TRANSACTION !!!  (parcel size = 18904324)
16:40:58.049  5095-5165  ContentResolver                 W  RemoteException: provider.call
16:40:58.052  5095-5165  ntProviderEndpointProxy         I  Immediate IPC retry failed, continuing with WakeupActivity

**Comment by microsoftjoe** [comment]
Hi @yaxin3690, the **_AgentInterruptedException_** happens when for some reason the Company Portal doesn't respond to a necessary IPC call. This is usually a sporadic failure. We check at process start for whether or not we can successfully make an IPC call to the Company Portal, and we'll display a dialog asking the user to exempt the Company Portal from battery restrictions. Please try again after exempting the Company Portal from battery restrictions.
If this is a persistent failure, please collect logs for us to analyze:
https://learn.microsoft.com/en-us/mem/intune/user-help/send-logs-to-your-it-admin-by-email-android

**Comment by rygo-msft** [comment]
It appears that this AgentInterruptedException is occurring when calling _reportFatalError_. Meaning we are trying to send the crash stack to the Company Portal and the app is already crashing.

We cannot investigate further without app logs (see Joe's request above) to indicate what the underlying crash stack is.

**Comment by yaxin3690** [comment]
The following Settings are required: Each application of the company needs to be changed from automatic startup to manual startup; Battery optimization off;

**Comment by yaxin3690** [comment]
The following Settings are required: Each application of the company needs to be changed from automatic startup to manual startup; Battery optimization off;
