### ISSUE TITLE
Crash with Security exception while accessing content resolver.

### ISSUE THREAD

**Issue by naquee-rizwan** [msintuneappsdk/ms-intune-app-sdk-android#139]
**Describe the bug:**
Crash with Security exception while accessing content resolver. In this scenario, application's content resolver is always resolving to intune sdk (like com.microsoft.windowsintune.companyportal).

**To Reproduce:**
The issue as per the stacktrace and logs seems to be intermittent but the crash rate is quite high. Also as per the analysis, user is trying to open a file to view it from third party apps (like Outlook). This crash is most probably happening for the managed accounts only (as most of the logs point the account to be enterprise managed) and is working properly if the user is not an enterprise user.

**Expected behavior:**
App should not crash and users should have a seamless experience using application.

**Screenshots and logs:**
```
Caused by java.lang.SecurityException: Permission Denial: opening provider androidx.core.content.FileProvider from ProcessRecord{518e95e 32481:com.adobe.reader/u0a301} (pid=32481, uid=10301) that is not exported from UID 10153
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
       at android.os.Parcel.createException(Parcel.java:2410)
       at android.os.Parcel.readException(Parcel.java:2393)
       at android.os.Parcel.readException(Parcel.java:2335)
       at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5910)
       at android.app.ActivityThread.acquireProvider(ActivityThread.java:7014)
       at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:3347)
       at android.content.ContentResolver.acquireProvider(ContentResolver.java:2510)
       at android.content.ContentResolver.call(ContentResolver.java:2445)
       at android.content.ContentResolver.call(ContentResolver.java:2430)
       at com.microsoft.intune.mam.client.content.ContentResolverIdentityOperations.call(ContentResolverIdentityOperations.java:24)
       at com.microsoft.intune.mam.client.content.ContentIdentityOperations.setCallingIdentity(ContentIdentityOperations.java:31)
       at com.microsoft.intune.mam.client.content.ContentResolverAccess.runWithIdentity(ContentResolverAccess.java:326)
       at com.microsoft.intune.mam.client.content.ContentManagementBase.readFromParcel(ContentManagementBase.java:117)
       at o.MediaBrowserCompat$CallbackHandler.a(MediaBrowserCompat.java:456)
       at o.MediaBrowserCompat$CallbackHandler.getType(MediaBrowserCompat.java:184)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(InterProxy.java:88)
       at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
       at $Proxy14.getType($Proxy14.java)
       at com.microsoft.intune.mam.client.content.MAMContentResolverManagement.getType(MAMContentResolverManagement.java:98)
       at com.adobe.libs.buildingblocks.utils.BBIntentUtils.getModifiedFileNameWithExtensionUsingIntentData(BBIntentUtils.java:140)
       at com.adobe.libs.buildingblocks.utils.BBIntentUtils.getFileSizeAndNameFromContentUri(BBIntentUtils.java:121)
       at com.adobe.libs.buildingblocks.utils.BBDownloadFileAsyncTask.doInBackground(BBDownloadFileAsyncTask.java:63)
       at com.adobe.libs.buildingblocks.utils.BBDownloadFileAsyncTask.doInBackground(BBDownloadFileAsyncTask.java:39)
       at android.os.AsyncTask$3.call(AsyncTask.java:394)
       at java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```

**Smartphone:**
This crash is not device specific. It is happening in various devices.

**Intune App SDK for Android:**
What version of the Intune SDK are you using? Are you using the latest version?
Version used - 8.3.0
What platform is your app based in (Java, Xamarin based, Cordova, etc)?
Native Android Application using Kotlin and Java.
For errors during build, does the app build without Intune SDK integration?
Not Applicable
For errors post build, does the app launch without being Intune SDK integrated?
Yes, this crash is most probably happening for enterprise users (as most of the logs point the account to be enterprise managed).
Who is the customer?
End Users
Do you see a trend with it only being reproduced on a specific device?
There is no particular trend of device / OS specification.

**Comment by bannus** [comment]
Thanks for the report. This is being tracked internally by #16263514.

**Comment by rygo-msft** [comment]
From our investigation, when an app makes a call into another ContentProvider, MAM first makes a call into that provider to declare the caller's identity. If the calling app does not have permission to interact with the destination provider a SecurityException is thrown.

Our understanding is that had MAM not made this call, the app's request would still result in a SecurityException being thrown for permission denial. We have taken a change in the mid-December release of the Company Portal to hopefully clarify this stack trace.

My recommendation is to investigate why you are trying to access ContentProviders that you do not have access to. In this case it appears that the target provider is not exported.

**Comment by naquee-rizwan** [comment]
Hi @rygo-msft,
Was this change made to clarify the stack trace? If so, do these crashes which started happening around Dec'28th are related to this update (Please note that these are IllegalStateException and not SecurityException)? **[Also, we had no releases for our app during this time period.]**
```
Caused by java.lang.IllegalStateException: Only owner is able to interact with pending/trashed item content://media/external/downloads/1000018023
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2449)
       at android.os.Parcel.createException(Parcel.java:2425)
       at android.os.Parcel.readException(Parcel.java:2408)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
       at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
       at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderProxy.java:780)
       at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2045)
       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1860)
       at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1693)
       at o.getServiceComponent.a(getServiceComponent.java:292)
       at com.microsoft.intune.mam.client.content.-$$Lambda$ContentResolverManagementBehaviorImpl$tXteXdG8K8RsK7iMZuzG_drV9qo.open(-.java:6)
       at o.getServiceComponent.a(getServiceComponent.java:557)
       at com.microsoft.intune.mam.client.content.-$$Lambda$ContentResolverManagementBehaviorImpl$_aoUOC3gRktSmNEiBs1WE0kdeOs.open(-.java:6)
       at com.microsoft.intune.mam.client.content.ContentManagementBase.CertificateInfo(ContentManagementBase.java:246)
       at com.microsoft.intune.mam.client.content.-$$Lambda$ContentManagementBase$tfuYU9bLIplybDKIZzkuZ3Jhgk4.call(-.java:4)
       at com.microsoft.intune.mam.client.content.-$$Lambda$vPVE1EiEnU_D54GFSPIWYSQCRqo.call(-.java:2)
       at com.microsoft.intune.mam.client.content.ContentResolverAccess.runWithIdentity(ContentResolverAccess.java:339)
       at com.microsoft.intune.mam.client.content.ContentManagementBase.readFromParcel(ContentManagementBase.java:117)
       at com.microsoft.intune.mam.client.content.ContentManagementBase.compareKeys(ContentManagementBase.java:500)
       at com.microsoft.intune.mam.client.content.ContentManagementBase.a(ContentManagementBase.java:246)
       at o.getServiceComponent.a(getServiceComponent.java:570)
       at o.getServiceComponent.openFileDescriptor(getServiceComponent.java:291)
       at o.getServiceComponent.openFileDescriptor(getServiceComponent.java:299)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(InterProxy.java:88)
       at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
       at $Proxy17.openFileDescriptor($Proxy17.java)
       at com.microsoft.intune.mam.client.content.MAMContentResolverManagement.openFileDescriptor(MAMContentResolverManagement.java:146)
```

```
Caused by java.lang.IllegalStateException: Only owner is able to interact with pending/trashed item content://media/external/downloads/1000038392
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2393)
       at android.os.Parcel.createException(Parcel.java:2369)
       at android.os.Parcel.readException(Parcel.java:2352)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
       at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
       at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderProxy.java:781)
       at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1993)
       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1808)
       at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1641)
       at o.setCallbacksMessenger.readFromParcel(setCallbacksMessenger.java:294)
       at com.microsoft.intune.mam.client.content.-$$Lambda$ContentResolverManagementBehaviorImpl$tXteXdG8K8RsK7iMZuzG_drV9qo.open(-.java:6)
       at o.setCallbacksMessenger.compareKeys(setCallbacksMessenger.java:559)
       at com.microsoft.intune.mam.client.content.-$$Lambda$ContentResolverManagementBehaviorImpl$_aoUOC3gRktSmNEiBs1WE0kdeOs.open(-.java:6)
       at com.microsoft.intune.mam.client.content.ContentManagementBase.describeContents(ContentManagementBase.java:281)
       at com.microsoft.intune.mam.client.content.-$$Lambda$ContentManagementBase$tfuYU9bLIplybDKIZzkuZ3Jhgk4.call(-.java:4)
       at com.microsoft.intune.mam.client.content.-$$Lambda$vPVE1EiEnU_D54GFSPIWYSQCRqo.call(-.java:2)
       at com.microsoft.intune.mam.client.content.ContentResolverAccess.runWithIdentity(ContentResolverAccess.java:366)
       at com.microsoft.intune.mam.client.content.ContentManagementBase.compareKeys(ContentManagementBase.java:121)
       at com.microsoft.intune.mam.client.content.ContentManagementBase.CertificateInfo(ContentManagementBase.java:535)
       at com.microsoft.intune.mam.client.content.ContentManagementBase.readFromParcel(ContentManagementBase.java:281)
       at o.setCallbacksMessenger.readFromParcel(setCallbacksMessenger.java:572)
       at o.setCallbacksMessenger.openFileDescriptor(setCallbacksMessenger.java:293)
       at o.setCallbacksMessenger.openFileDescriptor(setCallbacksMessenger.java:301)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(InterProxy.java:84)
       at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
       at $Proxy13.openFileDescriptor($Proxy13.java)
       at com.microsoft.intune.mam.client.content.MAMContentResolverManagement.openFileDescriptor(MAMContentResolverManagement.java:146)
```

**Comment by meghandaly** [comment]
@naquee-rizwan Yes, the change was made to clarify the stack trace. We will be making an additional change to handle `IllegalStateExceptions` as well so it is easier to diagnose why your app may be accessing `ContentResolvers` that you do not have access to, as Ryan stated.
