### ISSUE TITLE
Throws error when Firebase Cloud Messaging notification receives

### ISSUE THREAD

**Issue by Antarix** [msintuneappsdk/ms-intune-app-sdk-android#14]
`java.lang.LinkageError: Method void com.google.firebase.iid.FirebaseInstanceIdReceiver.onReceive(android.content.Context, android.content.Intent) overrides final method in class Lcom/microsoft/intune/mam/client/content/MAMBroadcastReceiver; (declaration of 'com.google.firebase.iid.FirebaseInstanceIdReceiver' appears in /data/app/com.linthub.yesinvest-34Od_Mwoj_3M02jWiDfOtg==/base.apk!classes2.dex)
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateReceiver(AppComponentFactory.java:84)
        at androidx.core.app.CoreComponentFactory.instantiateReceiver(CoreComponentFactory.java:54)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3539)
        at android.app.ActivityThread.access$1300(ActivityThread.java:235)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1779)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)`

**Comment by Huawei-yuan** [comment]
How do you solve this problem? thanks

**Comment by joakley-msft** [comment]
This issue is over a year old and does not contain enough information for us to take direct action. We have instituted new practices for monitoring issues regularly. Please re-open if this is still occurring.
