### ISSUE TITLE
Tests launch on Crash when using test-only modules.

### ISSUE THREAD

**Issue by shubhamgarg1** [msintuneappsdk/ms-intune-app-sdk-android#144]
**Describe the bug:**
Tests launch on Crash when using test-only modules.

**To Reproduce**
This is similar to the bug mentioned here: https://github.com/msintuneappsdk/ms-intune-app-sdk-android/issues/119
It is not crashing on app launch but now when we run the test-only module, it crashes.
We have created a test-only module using `com.android.test` plugin.

If we don't apply the intune plugin, everything works fine.

The project also has Hilt integration.

**Expected behavior:**
Tests should run without crashing.

**Screenshots and logs:**
- If your app is experiencing an issue post build, do you have app logs for the crash itself? Yes

```
  E AndroidRuntime: Process: com.adobe.reader, PID: 776
  E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application com.adobe.reader.MyApplication: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object com.microsoft.intune.mam.client.ComponentsContainer.get(java.lang.Class)' on a null object reference
  E AndroidRuntime: at android.app.LoadedApk.makeApplication(LoadedApk.java:1296)
  E AndroidRuntime: at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7152)
  E AndroidRuntime: at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7134)
  E AndroidRuntime: at android.app.ActivityThread.access$1500(ActivityThread.java:274)
  E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
  E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:107)
  E AndroidRuntime: at android.os.Looper.loop(Looper.java:237)
  E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8167)
  E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
  E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
  E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
  E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object com.microsoft.intune.mam.client.ComponentsContainer.get(java.lang.Class)' on a null object reference
  E AndroidRuntime: at com.microsoft.intune.mam.client.InterfaceComponentsAccess.get(InterfaceComponentsAccess.java:30)
  E AndroidRuntime: at com.microsoft.intune.mam.client.CachedBehaviorProvider.getComponent(CachedBehaviorProvider.java:42)
  E AndroidRuntime: at com.microsoft.intune.mam.client.CachedBehaviorProvider.get(CachedBehaviorProvider.java:33)
  E AndroidRuntime: at com.microsoft.intune.mam.client.content.pm.MAMPackageManagement.getBehavior(MAMPackageManagement.java:409)
  E AndroidRuntime: at com.microsoft.intune.mam.client.content.pm.MAMPackageManagement.getPackageInfo(MAMPackageManagement.java:228)
  E AndroidRuntime: at com.google.android.play.core.splitcompat.zze.<init>(com.google.android.play:core@@1.10.2:1)
  E AndroidRuntime: at com.google.android.play.core.splitcompat.SplitCompat.<init>(com.google.android.play:core@@1.10.2:2)
  E AndroidRuntime: at com.google.android.play.core.splitcompat.SplitCompat.zzi(com.google.android.play:core@@1.10.2:1)
  E AndroidRuntime: at com.google.android.play.core.splitcompat.SplitCompat.install(com.google.android.play:core@@1.10.2:1)
  E AndroidRuntime: at com.adobe.reader.MyApplication.attachBaseContext(ARApp.java:290)
  E AndroidRuntime: at android.app.Application.attach(Application.java:370)
  E AndroidRuntime: at android.app.Instrumentation.newApplication(Instrumentation.java:1157)
  E AndroidRuntime: at android.app.LoadedApk.makeApplication(LoadedApk.java:1288)
  E AndroidRuntime: ... 10 more
```

```
FATAL EXCEPTION: main
                                                                                                    Process: com.adobe.reader, PID: 30142
                                                                                                    java.lang.LinkageError: Method void com.adobe.reader.viewer.RAWAppCompatActivityWrapper.onActivityResult(int, int, android.content.Intent) overrides final method in class Lcom/microsoft/intune/mam/client/app/MAMActivity; (declaration of 'com.adobe.reader.viewer.RAWAppCompatActivityWrapper' appears in /data/app/~~2r66i0aIADcedXGRVsmJFg==/com.adobe.reader.devicetest-3BOFB3ZiQ47B5pHKAQWb4w==/base.apk!classes7.dex)
                                                                                                    	at com.adobe.reader.analytics.ARDCMAnalytics.getInstance(ARDCMAnalytics.java:111)
                                                                                                    	at com.adobe.reader.ARApp.onCreate(ARApp.java:371)
                                                                                                    	at com.adobe.reader.Hilt_ARProdApp.onCreate(Hilt_ARProdApp.java:40)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
                                                                                                    	at androidx.test.runner.MonitoringInstrumentation.callApplicationOnCreate(MonitoringInstrumentation.java:481)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6725)
                                                                                                    	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@19a6e82, Dispatchers.Main]
2022-12-22 23:21:44.836 30142-30251 connectors_debug   
```

**Smartphone (please complete the following information):**
All

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 9.1, Yes
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Java
- For errors during build, does the app build without Intune SDK integration? No
- For errors post build, does the app launch without being Intune SDK integrated? Yes
- Who is the customer? Adobe Acrobat
- Do you see a trend with it only being reproduced on a specific device? No

**Additional context:**
AGP version - 7.3.1
Gradle Wrapper version - 7.6

**Comment by shubhamgarg1** [comment]
I was able to find a solution to this issue by modifying how the Jacoco plugin was working. 
We were explicitly specifying the Jacoco versions:
```
            jacoco {
                version "0.8.8"
                toolVersion = "0.8.7"
            }

```

Removing the above fixed the issue.
