### ISSUE TITLE
Null Pointer Exception while building app

### ISSUE THREAD

**Issue by SACHDEVHITESH** [msintuneappsdk/ms-intune-app-sdk-android#148]
Post integrating the SDK and trying to build the app the app build is failing with the following error during mamifying the classes

> Task :library:transformClassesWithMamifyTransformForBetaDebug FAILED

Execution failed for task ':library:transformClassesWithMamifyTransformForBetaDebug'.

> java.lang.NullPointerException

This issue is causing the app to not be build

using javassit version 3.27.0-GA and the latest Intune SDK

Caused by: java.lang.NullPointerException
at javassist.ClassPool.cacheCtClass(ClassPool.java:236)
at javassist.CtClass.detach(CtClass.java:1427)
at com.microsoft.intune.mam.TransformationUnit.writeClassesToDirectory(TransformationUnit.java:275)
at com.microsoft.intune.mam.TransformationUnit.writeOutput(TransformationUnit.java:126)
at com.microsoft.intune.mam.BuildTimeMamifier.mamify(BuildTimeMamifier.java:131)
at com.microsoft.intune.mam.MamifyTransformBase.transform(MamifyTransformBase.java:195)
at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:284)
at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:69)

**Comment by bannus** [comment]
Not enough info to investigate -- please open a new issue and fill out the information in the template.
