### ISSUE TITLE
app crash on start in 9.1.10 SDK

### ISSUE THREAD

**Issue by SACHDEVHITESH** [msintuneappsdk/ms-intune-app-sdk-android#151]
java.lang.IllegalAccessError: Method 'void com.microsoft.intune.mam.client.app.MAMActivity.onActivityResult(int, int, android.content.Intent)' 
                                                                                                            at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                                                    	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
                                                                                                    	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
                                                                                                    	at android.app.Instrumentation.newActivity(Instrumentation.java:1256)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3503)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3771)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2172)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:237)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8163)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by SACHDEVHITESH** [comment]
@bannus can you update on the above issue

**Comment by SACHDEVHITESH** [comment]
@msintuneappsdk @msft-cofitz ^^

**Comment by bannus** [comment]
Not enough info to investigate -- please open a new issue and fill out the information in the template.
