### ISSUE TITLE
app crash on start in 9.1.10 SDK

### ISSUE THREAD

**Issue by SACHDEVHITESH** [msintuneappsdk/ms-intune-app-sdk-android#152]
**whenever we start the app the app crashes with the below error**

java.lang.IllegalAccessError: Method 'void com.microsoft.intune.mam.client.app.MAMActivity.onActivityResult(int, int, android.content.Intent)' implementing interface method 'void packagename.common.IBottomSheetListener.onActivityResult(int, int, android.content.Intent)' is not public (declaration of 'packagename.main.BaseMainActivityV2'
at java.lang.VMClassLoader.findLoadedClass(Native Method)
at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
at android.app.Instrumentation.newActivity(Instrumentation.java:1274)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3668)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3938)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:210)
at android.os.Looper.loop(Looper.java:299)
at android.app.ActivityThread.main(ActivityThread.java:8309)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

**The onActivityResult() is public in our project.**

**App specifications:**
minSdkVersion 28
targetSdkVersion 33
intunemam {
report = false
verify = true
incremental = true
}

**Comment by SACHDEVHITESH** [comment]
@bannus @msintuneappsdk @msft-cofitz 
please let me know what more information is needed

**Comment by meghandaly** [comment]
@SACHDEVHITESH There is not enough information in this issue for it to be actionable. There is an issue template available when opening and issue and it should be filled out as much as possible. 

Additionally, capturing [Company Portal logs](https://learn.microsoft.com/en-us/mem/intune/user-help/send-logs-to-your-it-admin-by-email-android) and sharing the Incident ID with our team will help us diagnose.

Please refer to our [integration guide](https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-android-phase1#stage-1-plan-the-integration) as well as that may help you proceed in your development.
