### ISSUE TITLE
Reading application's own content Uri gets blocked when read data policy is enabled

### ISSUE THREAD

**Issue by yilunc-gr** [msintuneappsdk/ms-intune-app-sdk-android#160]
**Describe the bug:**
Reading application's own content Uri gets blocked when read data policy is enabled.

**To Reproduce**
1. Go to Intune admin centre and update the policy "Receive data from other apps" as "None".
2. Click on "Save" and let device resync the policies.
3. Create a content Uri from the managed app using `FileProvider` APIs.
5. Read content Uri (e.g. calling `contentResolver::openAssetFileDescriptor`) from the same application in the same process

**Expected behavior:**
Reading internal content Uri shall work as normal while external Uri reading will be blocked.

**Screenshots and logs:**
Logs:
```
2023-03-21 14:55:38.389 26095-30986 ContentResolverAccess   pid-26095                            I  getAccessMode content type:application/pdf
2023-03-21 14:55:38.392 26095-30986 ageManagerPolicyFactory pid-26095                            I  Disallowing access to package <my-own-package>
2023-03-21 14:55:38.394 26095-30986 ageManagerPolicyFactory pid-26095                            I  Disallowing package <my-own-package> disallowed using RECEIVE_ONLY
2023-03-21 14:55:38.403 26095-30986 ContentResolverAccess   pid-26095                            I  Read disallowed by policy for ContentProvider <my-own-package>.fileprovider
2023-03-21 14:55:38.404 26095-30986 ContentManagementBase   pid-26095                            I  AccessMode for content authority <my-own-package>.fileprovider with content identity <user-email> is w under current identity <user-email> Allow my package: false
```

Stacktrace:
```
com.microsoft.intune.mam.client.content.ContentResolverFileAccessDeniedException
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at com.microsoft.intune.mam.InterProxy.readFromParcel(:498)
                                                                                                    	at com.microsoft.intune.mam.InterProxy.a(:33)
                                                                                                    	at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(:87)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy27.openFileDescriptor(Unknown Source)
                                                                                                    	at com.microsoft.intune.mam.client.content.MAMContentResolverManagement.openFileDescriptor(MAMContentResolverManagement.java:146)
```

**Smartphone (please complete the following information):**
 - Device: Any Android Device
 - OS: Tested on API Level 30

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
  Tested on latest version; The logs/stacktrace was taken from version Intune SDK version 9.1;

- What platform is your app based in?
   Kotlin/Java
- For errors during build, does the app build without Intune SDK integration?
  The content Uri behavior is normal in builds without Intune SDK integrated
- For errors post build, does the app launch without being Intune SDK integrated? N/A
- Who is the customer? N/A
- Do you see a trend with it only being reproduced on a specific device? 
  This behaviour is not related to a specific device.

**Comment by rygo-msft** [comment]
Hi @yilunc-gr, this is likely behaving by design as Intune will block accessing personal / unmanaged data into a managed user context when "Receive data from other apps" is set to "None".

Can you please provide more information to help us understand the specific scenario so we can offer guidance? What is the file identity for the data that you are trying to open? What is the current identity being used when you try to open the data? If possible, can you share a project that reproduces the issue?

Can you please reproduce the issue, upload logs, and share the incident ID following these steps https://learn.microsoft.com/en-us/mem/intune/user-help/send-logs-to-your-it-admin-by-email-android#send-logs-from-company-portal

**Comment by bannus** [comment]
@yilunc-gr, checking in on @rygo-msft's questions above. We'll plan to resolve this issue if we don't hear back.

**Comment by mcsimons** [comment]
@yilunc-gr thanks for that information. As was asked above, could you please reproduce the issue, upload logs and share the incident ID, you can find steps here: https://learn.microsoft.com/en-us/mem/intune/user-help/send-logs-to-your-it-admin-by-email-android#send-logs-from-company-portal_

**Comment by meghandaly** [comment]
@yilunc-gr Can you please provide the logs that we requested?

**Comment by bannus** [comment]
Closing due to inactivity, please re-open if needed.
