### ISSUE TITLE
Intune Problem in Android SDK 34

### ISSUE THREAD

**Issue by Nash123-start** [msintuneappsdk/ms-intune-app-sdk-android#169]
In Android SDK 34 
Safer dynamic code loading
If your app targets Android 14 and uses Dynamic Code Loading (DCL), all dynamically-loaded files must be marked as read-only. Otherwise, the system throws an exception. We recommend that apps [avoid dynamically loading code](https://developer.android.com/training/articles/security-tips#DynamicCode) whenever possible, as doing so greatly increases the risk that an app can be compromised by code injection or code tampering.

If you must dynamically load code, use the following approach to set the dynamically-loaded file (such as a DEX, JAR, or APK file) as read-only as soon as the file is opened and before any content is written:

https://developer.android.com/about/versions/14/behavior-changes-14

In Android sdk 34 we should set the dynamically-loaded file read only

When I use intune sdk in Android sdk 34 In found the problem:

      E  Proxy ClipboardManager Failed, setting flag in LocalSettings.
                                                                                                    java.lang.SecurityException: Writable dex file '/data/user/0/com.ringcentral.intune/cache/dx/android.content.ClipboardManager0.jar' is not allowed.
                                                                                                    	at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                                                                    	at dalvik.system.DexFile.openDexFile(DexFile.java:406)
                                                                                                    	at dalvik.system.DexFile.<init>(DexFile.java:128)
                                                                                                    	at dalvik.system.DexFile.<init>(DexFile.java:101)
                                                                                                    	at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)
                                                                                                    	at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
                                                                                                    	at dalvik.system.DexPathList.<init>(DexPathList.java:166)
                                                                                                    	at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:160)
                                                                                                    	at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:105)
                                                                                                    	at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:55)
                                                                                                    	at com.microsoft.intune.mam.client.ipcclient.proxy.CachingProxyBuilder.loadFromDexJar(:509)
                                                                                                    	at com.microsoft.intune.mam.client.ipcclient.proxy.CachingProxyBuilder.buildProxyClass(:469)

It seems not make the android.content.ClipboardManager0.jar read only so we can't not use intune sdk in android sdk 34

**Comment by meghandaly** [comment]
@Nash123-start The Android MAM SDK does not support Android 14/ API 34 at this time. Please understand that deploying your app with Android 14 targeting may leave your app open to data leaks as MAM enforcement will not fully be applied. 

We will be releasing a MAM SDK that supports Android 14 on/around when Google officially releases.
