### ISSUE TITLE
On upgrading to 5.6.0, app crashes on startup

### ISSUE THREAD

**Issue by NeilCannon** [msintuneappsdk/ms-intune-app-sdk-android#17]
Nexus 5X, Android 7.1.1
```
java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Bundle com.microsoft.intune.mam.client.ipc.AppPolicyEndpoint.prefetchCurrentFileEncryptionKey(java.lang.String)' on a null object reference
  at com.microsoft.intune.mam.client.ipcclient.MAMClientImpl.prefetchCurrentFileEncryptionKey(MAMClientImpl.java:509)
  at com.microsoft.intune.mam.client.fileencryption.FileEncryptionKeyCacheImpl.lambda$startKeyFetchAsync$128(FileEncryptionKeyCacheImpl.java:151)
  at com.microsoft.intune.mam.client.fileencryption.-$$Lambda$FileEncryptionKeyCacheImpl$j19Krfx5GlWZTPCO2vtNDQz2uSs.run(lambda:-1)
  at java.lang.Thread.run(Thread.java:761)
```

**Comment by joakley-msft** [comment]
This issue is obsolete, as it refers to a significantly outdated SDK version. We have instituted new practices for monitoring issues regularly. Please re-open if this is still occurring.
