### ISSUE TITLE
ANR: libmsmdmarp.so (Java_com_microsoft_intune_mam_client_fileencryption_FileEncryptionManager_installHooks)

### ISSUE THREAD

**Issue by shashank-msra** [msintuneappsdk/ms-intune-app-sdk-android#177]
# Intune Android App SDK ANR Issue

We are observing the following ANR solely on Android 14 OS across Pixel 7 & Pixel 7 Pro devices
```
main (native):tid=1 systid=21781 
#00 pc 0xb4f58 libc.so (fstatat64 + 8) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#01 pc 0x8b5fc libmsmdmarp.so (BuildId: 736afab37a1f7d5574dda2a3c806246f82d169fa)
#02 pc 0x55268 libmsmdmarp.so (BuildId: 736afab37a1f7d5574dda2a3c806246f82d169fa)
#03 pc 0x54e84 libmsmdmarp.so (BuildId: 736afab37a1f7d5574dda2a3c806246f82d169fa)
#04 pc 0x412d4 libmsmdmarp.so (BuildId: 736afab37a1f7d5574dda2a3c806246f82d169fa)
#05 pc 0x3ac5c libmsmdmarp.so (Java_com_microsoft_intune_mam_client_fileencryption_FileEncryptionManager_installHooks + 80) (BuildId: 736afab37a1f7d5574dda2a3c806246f82d169fa)
       at com.microsoft.intune.mam.client.fileencryption.FileEncryptionManager.installHooks(Native method)
       at com.microsoft.intune.mam.client.fileencryption.FileEncryptionManager.initNativeStateAndInstallHooks(:363)
       at com.microsoft.intune.mam.client.fileencryption.FileEncryptionManager.initialize(:538)
       at com.microsoft.intune.mam.client.ipcclient.MAMClientImpl.initialize(:348)
       at com.microsoft.intune.mam.client.ipcclient.MAMClientSingletonImpl.ensureInitialized(:81)
       at com.microsoft.intune.mam.client.app.ApplicationBehaviorImpl.attachBaseContext(:100)
       at java.lang.reflect.Method.invoke(Native method)
       at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(:84)
       at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
       at com.microsoft.intune.mam.client.app.ApplicationBehavior.attachBaseContext(SourceFile)
       at com.microsoft.intune.mam.client.app.MAMApplication$Impl.attachBaseContext(MAMApplication.java:88)
       at com.microsoft.intune.mam.client.app.MAMApplication.attachBaseContext(MAMApplication.java)
       at com.adobe.reader.ARApp.attachBaseContext(ARApp.java:311)
       at android.app.Application.attach(Application.java:346)
       at android.app.Instrumentation.newApplication(Instrumentation.java:1283)
       at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1458)
       at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1395)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6959)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication(unavailable)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8177)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

## Details

- **Intune Android App SDK Version: 9.1.0**
- **Android Device Make and Model: Pixel 7, Pixel 7 Pro**
- **Android Device OS Version: 14**

### Company Portal Logs
N/A. Issue reported on Firebase

### Complete ANR Logs
```
# Crashlytics - Stack trace
# Application: com.adobe.reader
# Platform: android
# Version: 23.8.0.29075.Beta (1928429075)
# Date: Fri Aug 25 2023 00:58:00 GMT+0530 (India Standard Time)
# Device: Pixel 7 (75%), Pixel 7 Pro (25%)
# OS: Android 14 (100%)
# Device States: Background (100%)

main (native):tid=1 systid=21781 
#00 pc 0xb4f58 libc.so (fstatat64 + 8) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#01 pc 0x8b5fc libmsmdmarp.so (BuildId: 736afab37a1f7d5574dda2a3c806246f82d169fa)
#02 pc 0x55268 libmsmdmarp.so (BuildId: 736afab37a1f7d5574dda2a3c806246f82d169fa)
#03 pc 0x54e84 libmsmdmarp.so (BuildId: 736afab37a1f7d5574dda2a3c806246f82d169fa)
#04 pc 0x412d4 libmsmdmarp.so (BuildId: 736afab37a1f7d5574dda2a3c806246f82d169fa)
#05 pc 0x3ac5c libmsmdmarp.so (Java_com_microsoft_intune_mam_client_fileencryption_FileEncryptionManager_installHooks + 80) (BuildId: 736afab37a1f7d5574dda2a3c806246f82d169fa)
       at com.microsoft.intune.mam.client.fileencryption.FileEncryptionManager.installHooks(Native method)
       at com.microsoft.intune.mam.client.fileencryption.FileEncryptionManager.initNativeStateAndInstallHooks(:363)
       at com.microsoft.intune.mam.client.fileencryption.FileEncryptionManager.initialize(:538)
       at com.microsoft.intune.mam.client.ipcclient.MAMClientImpl.initialize(:348)
       at com.microsoft.intune.mam.client.ipcclient.MAMClientSingletonImpl.ensureInitialized(:81)
       at com.microsoft.intune.mam.client.app.ApplicationBehaviorImpl.attachBaseContext(:100)
       at java.lang.reflect.Method.invoke(Native method)
       at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(:84)
       at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
       at com.microsoft.intune.mam.client.app.ApplicationBehavior.attachBaseContext(SourceFile)
       at com.microsoft.intune.mam.client.app.MAMApplication$Impl.attachBaseContext(MAMApplication.java:88)
       at com.microsoft.intune.mam.client.app.MAMApplication.attachBaseContext(MAMApplication.java)
       at com.adobe.reader.ARApp.attachBaseContext(ARApp.java:311)
       at android.app.Application.attach(Application.java:346)
       at android.app.Instrumentation.newApplication(Instrumentation.java:1283)
       at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1458)
       at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1395)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6959)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication(unavailable)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8177)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

FinalizerDaemon (waiting):tid=10 systid=21811 
       at java.lang.Object.wait(Native method)
       at java.lang.Object.wait(Object.java:386)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:210)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:231)
       at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:309)
       at java.lang.Daemons$Daemon.run(Daemons.java:145)
       at java.lang.Thread.run(Thread.java:1012)

ReferenceQueueDaemon (waiting):tid=14 systid=21810 
       at java.lang.Object.wait(Native method)
       at java.lang.Object.wait(Object.java:386)
       at java.lang.Object.wait(Object.java:524)
       at java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:239)
       at java.lang.Daemons$Daemon.run(Daemons.java:145)
       at java.lang.Thread.run(Thread.java:1012)

FinalizerWatchdogDaemon (waiting):tid=15 systid=21812 
       at java.lang.Object.wait(Native method)
       at java.lang.Object.wait(Object.java:386)
       at java.lang.Object.wait(Object.java:524)
       at java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded(Daemons.java:428)
       at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:408)
       at java.lang.Daemons$Daemon.run(Daemons.java:145)
       at java.lang.Thread.run(Thread.java:1012)

Intune MAM file logger (timed waiting):tid=19 systid=22028 
       at java.lang.Thread.sleep(Native method)
       at java.lang.Thread.sleep(Thread.java:450)
       at java.lang.Thread.sleep(Thread.java:355)
       at com.microsoft.intune.mam.log.ThreadedFileHandler$PublishRunner.run(:84)

Intune MAM enrollment retry (timed waiting):tid=20 systid=22032 
       at java.lang.Object.wait(Native method)
       at java.lang.Object.wait(Object.java:386)
       at android.os.ConditionVariable.block(ConditionVariable.java:128)
       at com.microsoft.intune.mam.policy.MAMWETaskQueue.getDueTasks(:91)
       at com.microsoft.intune.mam.policy.MAMWERetryScheduler$TaskRunner.run(:117)
       at java.lang.Thread.run(Thread.java:1012)

Signal Catcher (runnable):tid=2 systid=21802 
#00 pc 0x438168 libart.so (art::DumpNativeStack + 108) (BuildId: b221ddf9493596dec8a84b0692083bef)
#01 pc 0x474d3c libart.so (art::Thread::DumpStack const + 828) (BuildId: b221ddf9493596dec8a84b0692083bef)
#02 pc 0x474404 libart.so (art::DumpCheckpoint::Run + 208) (BuildId: b221ddf9493596dec8a84b0692083bef)
#03 pc 0x350198 libart.so (art::ThreadList::RunCheckpoint + 452) (BuildId: b221ddf9493596dec8a84b0692083bef)
#04 pc 0x7c64c0 libart.so (art::ThreadList::Dump + 1716) (BuildId: b221ddf9493596dec8a84b0692083bef)
#05 pc 0x7c5a7c libart.so (art::ThreadList::DumpForSigQuit + 744) (BuildId: b221ddf9493596dec8a84b0692083bef)
#06 pc 0x798d4c libart.so (art::Runtime::DumpForSigQuit + 56) (BuildId: b221ddf9493596dec8a84b0692083bef)
#07 pc 0x7a9764 libart.so (art::SignalCatcher::HandleSigQuit + 1320) (BuildId: b221ddf9493596dec8a84b0692083bef)
#08 pc 0x49e010 libart.so (art::SignalCatcher::Run + 312) (BuildId: b221ddf9493596dec8a84b0692083bef)
#09 pc 0xc9ccc libc.so (__pthread_start + 204) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#10 pc 0x5db00 libc.so (__start_thread + 64) (BuildId: 19c32900d9d702c303d2b4164fbba76c)

perfetto_hprof_listener (native):tid=4 systid=21803 
#00 pc 0xb4954 libc.so (read + 4) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#01 pc 0x25360 libperfetto_hprof.so (void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ArtPlugin_Initialize::$_7> > + 316) (BuildId: 45f1a9edf1901f1f4244fa490a5d943c)
#02 pc 0xc9ccc libc.so (__pthread_start + 204) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#03 pc 0x5db00 libc.so (__start_thread + 64) (BuildId: 19c32900d9d702c303d2b4164fbba76c)

ADB-JDWP Connection Control Thread (waiting):tid=8 systid=21805 
#00 pc 0xb5d38 libc.so (__ppoll + 8) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#01 pc 0x6984c libc.so (poll + 92) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#02 pc 0xa75c libadbconnection.so (adbconnection::AdbConnectionState::RunPollLoop + 724) (BuildId: 18d4f4b1c63b7f9ca4644652b670af77)
#03 pc 0x8ecc libadbconnection.so (adbconnection::CallbackFunction + 1456) (BuildId: 18d4f4b1c63b7f9ca4644652b670af77)
#04 pc 0xc9ccc libc.so (__pthread_start + 204) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#05 pc 0x5db00 libc.so (__start_thread + 64) (BuildId: 19c32900d9d702c303d2b4164fbba76c)

Jit thread pool worker thread 0 (native):tid=9 systid=21806 
#00 pc 0x5823c libc.so (syscall + 28) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#01 pc 0x22cfac libart.so (art::ConditionVariable::WaitHoldingLocks + 140) (BuildId: b221ddf9493596dec8a84b0692083bef)
#02 pc 0x5775c4 libart.so (art::ThreadPool::GetTask + 120) (BuildId: b221ddf9493596dec8a84b0692083bef)
#03 pc 0x577358 libart.so (art::ThreadPoolWorker::Run + 72) (BuildId: b221ddf9493596dec8a84b0692083bef)
#04 pc 0x577274 libart.so (art::ThreadPoolWorker::Callback + 164) (BuildId: b221ddf9493596dec8a84b0692083bef)
#05 pc 0xc9ccc libc.so (__pthread_start + 204) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#06 pc 0x5db00 libc.so (__start_thread + 64) (BuildId: 19c32900d9d702c303d2b4164fbba76c)

binder:21781_1 (native):tid=11 systid=21813 
#00 pc 0xb4c78 libc.so (__ioctl + 8) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#01 pc 0x66d4c libc.so (ioctl + 156) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#02 pc 0x8a19c libbinder.so (android::IPCThreadState::joinThreadPool + 348) (BuildId: 45ab483df008e45adea07b901590bf44)
#03 pc 0x8a028 libbinder.so (android::PoolThread::threadLoop + 24) (BuildId: 45ab483df008e45adea07b901590bf44)
#04 pc 0xfe18 libutils.so (android::Thread::_threadLoop + 584) (BuildId: 7208d9e8b9a0fc5c8a97683482fbb1eb)
#05 pc 0xe619c libandroid_runtime.so (android::AndroidRuntime::javaThreadShell + 140) (BuildId: 719733eeab67c81b548b6814ef6206f9)
#06 pc 0xc9ccc libc.so (__pthread_start + 204) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#07 pc 0x5db00 libc.so (__start_thread + 64) (BuildId: 19c32900d9d702c303d2b4164fbba76c)

binder:21781_2 (native):tid=12 systid=21814 
#00 pc 0xb4c78 libc.so (__ioctl + 8) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#01 pc 0x66d4c libc.so (ioctl + 156) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#02 pc 0x8a19c libbinder.so (android::IPCThreadState::joinThreadPool + 348) (BuildId: 45ab483df008e45adea07b901590bf44)
#03 pc 0x8a028 libbinder.so (android::PoolThread::threadLoop + 24) (BuildId: 45ab483df008e45adea07b901590bf44)
#04 pc 0xfe18 libutils.so (android::Thread::_threadLoop + 584) (BuildId: 7208d9e8b9a0fc5c8a97683482fbb1eb)
#05 pc 0xe619c libandroid_runtime.so (android::AndroidRuntime::javaThreadShell + 140) (BuildId: 719733eeab67c81b548b6814ef6206f9)
#06 pc 0xc9ccc libc.so (__pthread_start + 204) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#07 pc 0x5db00 libc.so (__start_thread + 64) (BuildId: 19c32900d9d702c303d2b4164fbba76c)

HeapTaskDaemon (waiting):tid=13 systid=21809 
#00 pc 0x58240 libc.so (syscall + 32) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#01 pc 0x2bb89c libart.so (art::ConditionVariable::TimedWait + 252) (BuildId: b221ddf9493596dec8a84b0692083bef)
#02 pc 0x393768 libart.so (art::gc::TaskProcessor::GetTask + 196) (BuildId: b221ddf9493596dec8a84b0692083bef)
#03 pc 0x393628 libart.so (art::gc::TaskProcessor::RunAllTasks + 52) (BuildId: b221ddf9493596dec8a84b0692083bef)
       at dalvik.system.VMRuntime.runHeapTasks(Native method)
       at java.lang.Daemons$HeapTaskDaemon.runInternal(Daemons.java:687)
       at java.lang.Daemons$Daemon.run(Daemons.java:145)
       at java.lang.Thread.run(Thread.java:1012)

binder:21781_3 (native):tid=16 systid=21862 
#00 pc 0xb4c78 libc.so (__ioctl + 8) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#01 pc 0x66d4c libc.so (ioctl + 156) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#02 pc 0x8a19c libbinder.so (android::IPCThreadState::joinThreadPool + 348) (BuildId: 45ab483df008e45adea07b901590bf44)
#03 pc 0x8a028 libbinder.so (android::PoolThread::threadLoop + 24) (BuildId: 45ab483df008e45adea07b901590bf44)
#04 pc 0xfe18 libutils.so (android::Thread::_threadLoop + 584) (BuildId: 7208d9e8b9a0fc5c8a97683482fbb1eb)
#05 pc 0xe619c libandroid_runtime.so (android::AndroidRuntime::javaThreadShell + 140) (BuildId: 719733eeab67c81b548b6814ef6206f9)
#06 pc 0xc9ccc libc.so (__pthread_start + 204) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#07 pc 0x5db00 libc.so (__start_thread + 64) (BuildId: 19c32900d9d702c303d2b4164fbba76c)

Profile Saver (native):tid=17 systid=21941 
#00 pc 0x5823c libc.so (syscall + 28) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#01 pc 0x22cfac libart.so (art::ConditionVariable::WaitHoldingLocks + 140) (BuildId: b221ddf9493596dec8a84b0692083bef)
#02 pc 0x400a3c libart.so (art::ProfileSaver::Run + 848) (BuildId: b221ddf9493596dec8a84b0692083bef)
#03 pc 0x3fce54 libart.so (art::ProfileSaver::RunProfileSaverThread + 152) (BuildId: b221ddf9493596dec8a84b0692083bef)
#04 pc 0xc9ccc libc.so (__pthread_start + 204) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#05 pc 0x5db00 libc.so (__start_thread + 64) (BuildId: 19c32900d9d702c303d2b4164fbba76c)

Intune MAM Unmanaged IPC-0 (timed waiting):tid=18 systid=22005 
       at jdk.internal.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
       at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401)
       at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1131)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)

Intune MAM telemetry (waiting):tid=21 systid=22030 
       at jdk.internal.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
       at java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3466)
       at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3437)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623)
       at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:420)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1071)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1131)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)

queued-work-looper (native):tid=22 systid=22034 
#00 pc 0xb5c38 libc.so (__epoll_pwait + 8) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
#01 pc 0xf1bc libutils.so (android::Looper::pollOnce + 204) (BuildId: 7208d9e8b9a0fc5c8a97683482fbb1eb)
#02 pc 0x17fe0c libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce + 44) (BuildId: 719733eeab67c81b548b6814ef6206f9)
       at android.os.MessageQueue.nativePollOnce(Native method)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:162)
       at android.os.Looper.loop(Looper.java:294)
       at android.os.HandlerThread.run(HandlerThread.java:67)

Intune MAM background-0 (timed waiting):tid=23 systid=22036 
       at jdk.internal.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
       at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401)
       at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1131)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)

Intune MAM IPC-0 (timed waiting):tid=24 systid=22037 
       at jdk.internal.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
       at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401)
       at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1131)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
```

## AndroidX Dependencies

If your app includes any AndroidX libraries, please list them here, along with the version info:
androidxCore = "1.6.0"
androidxLifecycle = "2.3.1"
androidxWorkManager = "2.7.0"
androidxNavigation = "2.5.2"
androidxStartupRuntime = "1.1.0"
androidxDatastore = "1.0.0"

## Third-Party Library Dependencies

If your app includes any third-party libraries, please list them here, along with the version info:

- NA

[Intune App SDK for Android Integration Guide]: https://learn.microsoft.com/mem/intune/developer/app-sdk-android-phase1
[Report a problem in Company Portal or Intune app for Android]: https://learn.microsoft.com/mem/intune/user-help/send-logs-to-your-it-admin-by-email-android
[Microsoft Intune App SDK for Android]: https://github.com/msintuneappsdk/ms-intune-app-sdk-android
[SDK]: https://github.com/msintuneappsdk/ms-intune-app-sdk-android/releases

**Comment by shashank-msra** [comment]
YES, OS is Android 14 for 99% cases & < 1% Android 13.
The devices in which this has occurred are all Google Pixel devices (probably the only ones getting early stage Android 14). 

Occurrences are rising at little more pace. 460 ANRs across 86 users now.

**Comment by singh-srikant** [comment]
Hi @Archit-Pikle, do you have any update on this or reason why it could be occurring ? If this issue is being addressed, in which Intune version is it expected to be fixed ?

 It has spiked in Oct'23 release and now has 3,753 ANR events affecting 778 users over last 30 days.

**Comment by bannus** [comment]
We are tracking this issue, but no updates to share at this time.

###### Internal tracking #26816141
