### ISSUE TITLE
[.NET MAUI] Application crash on startup

### ISSUE THREAD

**Issue by leoslima1** [msintuneappsdk/ms-intune-app-sdk-android#181]
# Intune Android App SDK for .NET MAUI Issue

## Summary

The application is crashing right after the startup on Android. **Java.Lang.RuntimeException**: `Unable to get provider androidx.startup.InitializationProvider: android.content.res.Resources$NotFoundException: String resource ID #0x7f10001b`

I have all the configurations made on `AndroidManifest.xml` like adding the meta-data for `com.microsoft.intune.mam.aad.ClientId`, also have the `microsoft.identity.client.BrowserTabActivity` for MSAL authentication.

Before the application crash, i'm getting this from log:

[MAMInfo] MAMInfo initialized. Debug=false, Agent=PRODUCTION, ManagedDialogDisabled=false, PolicyRequired=false, MultiIdentityEnabled=false, FullBackupContent=true, DataExtractionRules=true, UseDefaultEnrollment=false, ExceptionOnInit=false, Debuggable=true, IsolatedProcessesAllowed=false
[MAMComponents] Not initializing MAM classes because the MDM package is not installed.
[MAMComponents] Not initializing MAM classes because the MDM package is not installed.

## Details

- **`Microsoft.Intune.Maui.Essentials.android` Version:*9.5.2-beta2**
- **Operating System (Mac, Linux, Windows) and Version**: Windows 11
- **Visual Studio Version**: Visual Studio 2022 17.7.3

## Logs

For **build issues**, please include:

- MSBuild Logs

[MAMInfo] MAMInfo initialized. Debug=false, Agent=PRODUCTION, ManagedDialogDisabled=false, PolicyRequired=false, MultiIdentityEnabled=false, FullBackupContent=true, DataExtractionRules=true, UseDefaultEnrollment=false, ExceptionOnInit=false, Debuggable=true, IsolatedProcessesAllowed=false
[MAMComponents] Not initializing MAM classes because the MDM package is not installed.
[MAMComponents] Not initializing MAM classes because the MDM package is not installed.

## Questions to Ask Before Submission

1. Does the app build and launch without including the `Microsoft.Intune.Maui.Essentials.android` package? **YES**
2. Does the issue reproduce if you rebuild after deleting the `bin` and `obj` output folders? **YES**
3. Have you checked the [.NET MAUI repository](https://github.com/dotnet/maui/issues) for similar issues? If so, please follow the guidance there or add that information to this issue. **Nothing related**
4. Are you using the latest `Microsoft.Intune.Maui.Essentials.android` NuGet package version? **YES**

**Comment by rygo-msft** [comment]
@leoslima1 can you provide more information about the crash?
What is the crash stack?
What resource is trying to be accessed?

**Comment by leoslima1** [comment]
Hey @rygo-msft thank you for the response.

Actually the call stack is empty, just appear "[External Code]".
I'm not trying to access any resource, it should be something related to the Intune.

The only message that appear is:

**Java.Lang.RuntimeException**: `Unable to get provider androidx.startup.InitializationProvider: android.content.res.Resources$NotFoundException: String resource ID #0x7f10001b`

And that's what I have from output:

`[aione.nexus.dev] Resource 7f10001b is a complex map type.
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.chaione.nexus.dev, PID: 2420
[AndroidRuntime] java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: android.content.res.Resources$NotFoundException: String resource ID #0x7f10001b
[AndroidRuntime] 	at android.app.ActivityThread.installProvider(ActivityThread.java:7493)
[AndroidRuntime] 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6999)
[AndroidRuntime] 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6770)
[AndroidRuntime] 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[AndroidRuntime] 	at android.os.Looper.loopOnce(Looper.java:201)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:288)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7898)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[AndroidRuntime] Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f10001b
[AndroidRuntime] 	at android.content.res.Resources.getText(Resources.java:453)
[AndroidRuntime] 	at android.content.res.Resources.getString(Resources.java:546)
[AndroidRuntime] 	at android.content.Context.getString(Context.java:762)
[AndroidRuntime] 	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:216)
[AndroidRuntime] 	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
[AndroidRuntime] 	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
[AndroidRuntime] 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
[AndroidRuntime] 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
[AndroidRuntime] 	at android.app.ActivityThread.installProvider(ActivityThread.java:7488)
[AndroidRuntime] 	... 11 more
Loaded assembly: System.Console.dll [External]
`

**Comment by rygo-msft** [comment]
@leoslima1 This is unfortunately not sufficient information to begin an investigation. According to the stack trace, the failure is occurring while initializing a ContentProvider, additional logcat context should indicate what that provider is. Information in the AndroidManifest.xml should also help to identify what resources the provider might be attempting to reference.

Please share logcat logs capturing the time from app launch to app crash.

**Comment by leoslima1** [comment]
@rygo-msft here's the logcat:

` Time | Device Name | Type | PID | Tag | Message
-- | -- | -- | -- | -- | --
  | Google Pixel 4 | Info | 6188 | MonoDroid | UNHANDLED EXCEPTION:
  | Google Pixel 4 | Info | 6188 | MonoDroid |  
  | Google Pixel 4 | Info | 6188 | MonoDroid | Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f10001b	at android.content.res.Resources.getText(Resources.java:453)	at android.content.res.Resources.getString(Resources.java:546)	at android.content.Context.getString(Context.java:762)	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:216)	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)	at android.app.ActivityThread.installProvider(ActivityThread.java:7488)	... 11 more
  | Google Pixel 4 | Info | 6188 | MonoDroid | java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: android.content.res.Resources$NotFoundException: String resource ID #0x7f10001b	at android.app.ActivityThread.installProvider(ActivityThread.java:7493)	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6999)	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6770)	at android.app.ActivityThread.-$Nest$mhandleBindApplication(Unknown Source:0)	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)	at android.os.Handler.dispatchMessage(Handler.java:106)	at android.os.Looper.loopOnce(Looper.java:201)	at android.os.Looper.loop(Looper.java:288)	at android.app.ActivityThread.main(ActivityThread.java:7898)	at java.lang.reflect.Method.invoke(Native Method)	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
  | Google Pixel 4 | Info | 6188 | MonoDroid | --- End of managed Java.Lang.RuntimeException stack trace ---
  | Google Pixel 4 | Info | 6188 | MonoDroid | Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f10001b	at android.content.res.Resources.getText(Resources.java:453)	at android.content.res.Resources.getString(Resources.java:546)	at android.content.Context.getString(Context.java:762)	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:216)	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)	at android.app.ActivityThread.installProvider(ActivityThread.java:7488)	... 11 more
  | Google Pixel 4 | Info | 6188 | MonoDroid | java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: android.content.res.Resources$NotFoundException: String resource ID #0x7f10001b	at android.app.ActivityThread.installProvider(ActivityThread.java:7493)	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6999)	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6770)	at android.app.ActivityThread.-$Nest$mhandleBindApplication(Unknown Source:0)	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)	at android.os.Handler.dispatchMessage(Handler.java:106)	at android.os.Looper.loopOnce(Looper.java:201)	at android.os.Looper.loop(Looper.java:288)	at android.app.ActivityThread.main(ActivityThread.java:7898)	at java.lang.reflect.Method.invoke(Native Method)	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
  | Google Pixel 4 | Info | 6188 | MonoDroid | --- End of managed Java.Lang.RuntimeException stack trace ---
  | Google Pixel 4 | Info | 6188 | MonoDroid | --- End of inner exception stack trace ---
  | Google Pixel 4 | Info | 6188 | MonoDroid | android.content.res.Resources$NotFoundException: String resource ID #0x7f10001b	at android.content.res.Resources.getText(Resources.java:453)	at android.content.res.Resources.getString(Resources.java:546)	at android.content.Context.getString(Context.java:762)	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:216)	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)	at android.app.ActivityThread.installProvider(ActivityThread.java:7488)	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6999)	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6770)	at android.app.ActivityThread.-$Nest$mhandleBindApplication(Unknown Source:0)	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)	at android.os.Handler.dispatchMessage(Handler.java:106)	at android.os.Looper.loopOnce(Looper.java:201)	at android.os.Looper.loop(Looper.java:288)	at android.app.ActivityThread.main(ActivityThread.java:7898)	at java.lang.reflect.Method.invoke(Native Method)	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
  | Google Pixel 4 | Info | 6188 | MonoDroid | --- End of managed Android.Content.Res.Resources+NotFoundException stack trace ---
  | Google Pixel 4 | Info | 6188 | MonoDroid | android.content.res.Resources$NotFoundException: String resource ID #0x7f10001b	at android.content.res.Resources.getText(Resources.java:453)	at android.content.res.Resources.getString(Resources.java:546)	at android.content.Context.getString(Context.java:762)	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:216)	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)	at android.app.ActivityThread.installProvider(ActivityThread.java:7488)	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6999)	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6770)	at android.app.ActivityThread.-$Nest$mhandleBindApplication(Unknown Source:0)	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)	at android.os.Handler.dispatchMessage(Handler.java:106)	at android.os.Looper.loopOnce(Looper.java:201)	at android.os.Looper.loop(Looper.java:288)	at android.app.ActivityThread.main(ActivityThread.java:7898)	at java.lang.reflect.Method.invoke(Native Method)	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
  | Google Pixel 4 | Info | 6188 | MonoDroid | --- End of managed Android.Content.Res.Resources+NotFoundException stack trace ---
  | Google Pixel 4 | Info | 6188 | MonoDroid | Java.Lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: android.content.res.Resources$NotFoundException: String resource ID #0x7f10001b ---> Android.Content.Res.Resources+NotFoundException: String resource ID #0x7f10001b`

And here is the manifest file:

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
  <application android:allowBackup="true" android:icon="@mipmap/appicon" android:roundIcon="@mipmap/appicon_round" android:supportsRtl="true"
               android:backupAgent="com.microsoft.intune.mam.client.app.backup.MAMDefaultBackupAgent">
    <meta-data
            android:name="com.microsoft.intune.mam.aad.ClientID"
            android:value="[my client id]" />
    <meta-data
            android:name="com.microsoft.intune.mam.aad.Authority"
            android:value="https://login.microsoftonline.com/[my tenant id]" />
    <meta-data
            android:name="com.microsoft.intune.mam.aad.NonBrokerRedirectURI"
            android:value="msauth.[my bundle id]://auth" />
    <activity android:name="microsoft.identity.client.BrowserTabActivity" android:exported="true">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="msal[my client id]" android:host="auth" />
      </intent-filter>
    </activity>
  </application>
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.INTERNET" />
  <queries>
    <package android:name="com.azure.authenticator" />
    <package android:name="[my bundle id]" />
    <package android:name="com.microsoft.windowsintune.companyportal" />
  </queries>
</manifest>`

**Comment by meghandaly** [comment]
@leoslima1 Hmm... there is nothing that is indicating MAM is responsible for the crash. 

Can you share what additional NuGet packages are referenced by your app? It is possible there is code we did not anticipate being intercepted by the MAM SDK.

**Comment by leoslima1** [comment]
Hey @meghandaly of course I can share my nuget packages. I'm also questioning myself what can be happening, but no luck looking at the logs.

Here's my packages:

`	<ItemGroup Condition="$(TargetFramework.Contains('android'))">
		<PackageReference Include="Microsoft.Intune.Maui.Essentials.android" Version="9.5.2-beta2" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AlohaKit.Animations" Version="1.0.0" />
		<PackageReference Include="CommunityToolkit.Maui" Version="5.3.0" />
		<PackageReference Include="DryIoc.Microsoft.DependencyInjection.Extension" Version="1.0.0.2" />
		<PackageReference Include="IeuanWalker.Maui.Switch" Version="1.0.4" />
		<PackageReference Include="LiveChartsCore.SkiaSharpView.Maui" Version="2.0.0-beta.920" />
		<PackageReference Include="Microsoft.AppCenter.Analytics" Version="5.0.2" />
		<PackageReference Include="Microsoft.AppCenter.Crashes" Version="5.0.2" />
		<PackageReference Include="Microsoft.Extensions.Http.Polly" Version="7.0.10" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="7.0.0" />
		<PackageReference Include="Microsoft.Identity.Client" Version="4.55.0" />
		<PackageReference Include="Mobile.BuildTools" Version="2.0.245" />
		<PackageReference Include="Mopups" Version="1.1.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Polly" Version="7.2.4" />
		<PackageReference Include="Prism.DryIoc.Maui" Version="8.1.273-pre" />
		<PackageReference Include="Prism.Maui" Version="8.1.273-pre" />
		<PackageReference Include="ReactiveProperty" Version="9.3.1" />
		<PackageReference Include="Refit.HttpClientFactory" Version="7.0.0" />
		<PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="2.88.5" />
		<PackageReference Include="TimePeriodLibrary.NET" Version="2.1.3" />
	</ItemGroup>`

**Comment by meghandaly** [comment]
@leoslima1 thank you!

Additional investigation revealed `0x7F10001B` is associated with AndroidX Startup.

From `Resource.designer.cs`:
```
// aapt resource value: 0x7F10001B
public const int androidx_startup = 2131755035;
```

If you inspect your app's `Resource.designer.cs` (typically located in `obj/{Configuration}/{TargetFramework}/designtime`) do you have that value?

Can you also share the relevant snippets from your merged `AndroidManifest.xml` (typically located in `obj/{Configuration}/{TargetFramework}/android/manifest`)?

For example, ours contains:
```
    <provider android:name="androidx.startup.InitializationProvider" android:authorities="com.microsoft.intune.mam.maui.testapp.androidx-startup" android:exported="false" tools:node="merge">
      <meta-data android:name="androidx.lifecycle.ProcessLifecycleInitializer" android:value="androidx.startup" />
      <meta-data android:name="androidx.emoji2.text.EmojiCompatInitializer" android:value="androidx.startup" />
    </provider>
```

And any references to the `InitializationProvider` in your manifest would be helpful to inspect.

**Comment by meghandaly** [comment]
@leoslima1 are you able to share the requested info?

**Comment by leoslima1** [comment]
Hey @meghandaly of course I can share with you, I can't do it right now, because i'm traveling and did not bring my laptop, I'll be back this week, and will share with you as soon as possible. Thank you

**Comment by leoslima1** [comment]
Hi @meghandaly I could get the values for you:

That's the `androidx_startup` value on `Resource.designer.cs`

```
// aapt resource value: 0x7F0F001B
public const int androidx_startup = 2131689499;
```

Here's the full manifest after build:

```
<?xml version="1.0" encoding="utf-8"?>
<!--
    This code was generated by a tool.
    It was generated from C:\ChaiOne\Nexus\nexus-mobile\Nexus.Mobile\Platforms\Android\AndroidManifest.xml
    Changes to this file may cause incorrect behavior and will be lost if
    the contents are regenerated.
-->
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools" package="com.constellation.nexus" android:versionCode="1" android:versionName="1.0">
  <uses-sdk android:minSdkVersion="33" android:targetSdkVersion="33" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.INTERNET" />
  <queries>
    <package android:name="com.azure.authenticator" />
    <package android:name="com.constellation.nexus" />
    <package android:name="com.microsoft.windowsintune.companyportal" />
  </queries>
  <permission android:name="com.constellation.nexus.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION" android:protectionLevel="signature" />
  <uses-permission android:name="com.constellation.nexus.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION" />
  <application android:name="crc643ae941c56df88757.MainApplication" android:allowBackup="true" android:appComponentFactory="androidx.core.app.CoreComponentFactory" android:backupAgent="com.microsoft.intune.mam.client.app.backup.MAMDefaultBackupAgent" android:debuggable="true" android:extractNativeLibs="true" android:icon="@mipmap/appicon" android:label="Nexus" android:roundIcon="@mipmap/appicon_round" android:supportsRtl="true" tools:ignore="MissingApplicationIcon">
    <meta-data android:name="com.microsoft.intune.mam.aad.ClientID" android:value="dc244566-769e-4071-87a4-415373ab40df" />
    <meta-data android:name="com.microsoft.intune.mam.aad.Authority" android:value="https://login.microsoftonline.com/d8fb9c07-c19e-4e8c-a1cb-717cd3cf8ffe" />
    <meta-data android:name="com.microsoft.intune.mam.aad.NonBrokerRedirectURI" android:value="msauth.com.constellation.nexus://auth" />
    <activity android:name="crc648316b0a9aa8cfd61.BrowserTabActivity" android:exported="true">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:host="auth" android:scheme="msaldc244566-769e-4071-87a4-415373ab40df" />
      </intent-filter>
    </activity>
    <activity android:name="crc643ae941c56df88757.MainActivity" android:configChanges="density|orientation|smallestScreenSize|screenLayout|screenSize|uiMode" android:exported="true" android:theme="@style/SplashTheme">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
    <activity android:name="crc6468b6408a11370c2f.WebAuthenticatorIntermediateActivity" android:configChanges="orientation|screenSize" android:exported="true" />
    <provider android:name="microsoft.maui.essentials.fileProvider" android:authorities="com.constellation.nexus.fileProvider" android:exported="false" android:grantUriPermissions="true">
      <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/microsoft_maui_essentials_fileprovider_file_paths" />
    </provider>
    <receiver android:name="crc64e53d2f592022988e.ConnectivityBroadcastReceiver" android:enabled="true" android:exported="false" android:label="Essentials Connectivity Broadcast Receiver" />
    <activity android:name="crc64ba438d8f48cf7e75.IntermediateActivity" android:configChanges="orientation|screenSize" android:exported="true" />
    <receiver android:name="crc640a8d9a12ddbf2cf2.BatteryBroadcastReceiver" android:enabled="true" android:exported="false" android:label="Essentials Battery Broadcast Receiver" />
    <receiver android:name="crc640a8d9a12ddbf2cf2.EnergySaverBroadcastReceiver" android:enabled="true" android:exported="false" android:label="Essentials Energy Saver Broadcast Receiver" />
    <activity android:name="microsoft.identity.client.AuthenticationActivity" android:exported="true" />
    <activity android:name="crc64ed1888fb4925e3b7.AuthenticationAgentActivity" android:configChanges="orientation|screenSize" android:exported="true" />
    <service android:name="crc64396a3fe5f8138e3f.KeepAliveService" />
    <provider android:name="mono.MonoRuntimeProvider" android:authorities="com.constellation.nexus.mono.MonoRuntimeProvider.__mono_init__" android:exported="false" android:initOrder="1999999999" />
    <provider android:name="androidx.startup.InitializationProvider" android:authorities="com.constellation.nexus.androidx-startup" android:exported="false" tools:node="merge">
      <meta-data android:name="androidx.lifecycle.ProcessLifecycleInitializer" android:value="androidx.startup" />
      <meta-data android:name="androidx.emoji2.text.EmojiCompatInitializer" android:value="androidx.startup" />
    </provider>
    <uses-library android:name="androidx.window.extensions" android:required="false" />
    <uses-library android:name="androidx.window.sidecar" android:required="false" />
    <service android:name="com.microsoft.intune.mam.client.notification.MAMNotificationReceiverService" android:exported="true" android:label="" tools:ignore="ExportedService">
      <!--
            Note: if adding an intent-filter, ensure all users of this component create intents
            that match at least one filter. For details, refer to the following Android docs:
            https://developer.android.com/about/versions/13/behavior-changes-13#intent-filters
            -->
    </service>
    <service android:name="com.microsoft.intune.mam.client.service.MAMBackgroundService" android:exported="false" android:label="" />
    <service android:name="com.microsoft.intune.mam.client.service.MAMBackgroundJobService" android:exported="false" android:label="" android:permission="android.permission.BIND_JOB_SERVICE" />
    <receiver android:name="com.microsoft.intune.mam.client.service.MAMBackgroundReceiver" android:exported="true">
      <intent-filter>
        <action android:name="android.intent.action.DOWNLOAD_COMPLETE" />
      </intent-filter>
    </receiver>
    <activity android:name="com.microsoft.intune.mam.client.app.offline.OfflineStartupBlockedActivity" android:exported="false" android:multiprocess="true" />
    <activity android:name="com.microsoft.intune.mam.client.app.offline.OfflineRestartRequiredActivity" android:exported="false" android:multiprocess="true" />
    <activity android:name="com.microsoft.intune.mam.client.app.startup.MAMStartupActivity" android:exported="false" android:multiprocess="true" />
    <!--
             MAMResolverActivity has taskAffinity="" instead of the default one (the app's defaultAffinity).
             This way when we prompt (e.g. install Managed Browser), the system doesn't bring up some existing
             task record that confuses UI.
        -->
    <activity android:name="com.microsoft.intune.mam.client.app.resolver.MAMResolverActivity" android:exported="false" android:taskAffinity="" android:theme="@style/MAMDialogTheme" />
    <activity android:name="com.microsoft.intune.mam.client.app.offline.OfflineInstallCompanyPortalDialogActivity" android:exported="false" android:multiprocess="true" android:theme="@style/MAMDialogTheme" />
    <activity android:name="com.microsoft.intune.mam.client.app.offline.OfflineNotifyWipeActivity" android:exported="false" />
    <activity android:name="com.microsoft.intune.mam.client.app.startup.MAMComplianceBlockActivity" android:exported="false" android:label="ComplianceBlock" />
  </application>
</manifest>
```

Let me know if you need something else.
Thanks
Leo

**Comment by leoslima1** [comment]
Hey @meghandaly any news?
Also would be great if you guys could create a sample with basic functionalities, it will be easier to us to understand the configuration process and how to integrate with our apps.

**Comment by leoslima1** [comment]
Hey @meghandaly any news about that issue?

**Comment by leoslima1** [comment]
Hi @meghandaly @rygo-msft can you guys help me on that, i'm still getting the same issue, even after upgrading to .net 8

**Comment by leoslima13** [comment]
@meghandaly @rygo-msft this issue can be closed, this is not happening anymore using .net 8 and also the latest version of sdk
