### ISSUE TITLE
java.lang.NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by jason8232590** [msintuneappsdk/ms-intune-app-sdk-android#2]
Caused by: java.lang.NullPointerException: Attempt to get length of null array
                                                      at com.microsoft.intune.mam.client.app.WrappedAppReflectionUtilsBehaviorImpl.parametersToString(WrappedAppReflectionUtilsBehaviorImpl.java:190)
                                                      at com.microsoft.intune.mam.client.app.WrappedAppReflectionUtilsBehaviorImpl.getMethod(WrappedAppReflectionUtilsBehaviorImpl.java:78)
                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                      at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(InterProxy.java:72)
                                                      at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                      at $Proxy16.getMethod(Unknown Source)
                                                      at com.microsoft.intune.mam.client.app.WrappedAppReflectionUtils.getMethod(WrappedAppReflectionUtils.java:98)
                                                      at com.google.android.exoplayer2.audio.AudioTrack.<init>(AudioTrack.java:314)
                                                      at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.<init>(MediaCodecAudioRenderer.java:133)

///////////////////////////////////////////////////////////////////////////////////

//code from exoplayer

///////////////////////////////////////////////////////////////////////////////////
public AudioTrack(AudioCapabilities audioCapabilities, Listener listener) {
    this.audioCapabilities = audioCapabilities;
    this.listener = listener;
    releasingConditionVariable = new ConditionVariable(true);
    if (Util.SDK_INT >= 18) {
      try {
        getLatencyMethod =
            android.media.AudioTrack.class.getMethod("getLatency", (Class<?>[]) null);   // crash log   at com.google.android.exoplayer2.audio.AudioTrack.<init>(AudioTrack.java:314)
      } catch (NoSuchMethodException e) {
        // There's no guarantee this method exists. Do nothing.
      }
    }
    if (Util.SDK_INT >= 23) {
      audioTrackUtil = new AudioTrackUtilV23();
    } else if (Util.SDK_INT >= 19) {
      audioTrackUtil = new AudioTrackUtilV19();
    } else {
      audioTrackUtil = new AudioTrackUtil();
    }
    playheadOffsets = new long[MAX_PLAYHEAD_OFFSET_COUNT];
    volume = 1.0f;
    startMediaTimeState = START_NOT_SET;
    streamType = C.STREAM_TYPE_DEFAULT;
  }

I encountered a bug when I  played a video on a app with intune wrapped .The log show as above. Can you help me to fix it ? Thanks anyway.

**Comment by joakley-msft** [comment]
This issue is over a year old and does not contain enough information for us to take direct action. We have instituted new practices for monitoring issues regularly. Please re-open if this is still occurring.
