### ISSUE TITLE
crash observed in android 13 devices while launching Installed activity

### ISSUE THREAD

**Issue by ravish2038** [msintuneappsdk/ms-intune-app-sdk-android#214]
# Intune Android App SDK for .NET MAUI Issue

## Summary

crash observed in android 13 devices while launching Installed application's activity , might be New restriction from Android to call 
explicit Activity 
## Details

- **`Microsoft.Intune.Maui.Essentials.android` Version:** 10.0.0
- **Operating System: Android 13

## Logs

02-07 16:58:38.120 10303 7721 7721 E AndroidRuntime: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.boxer.email/com.boxer.unified.compose.ComposeActivityExternal}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
02-07 16:58:38.120 10303 7721 7721 E AndroidRuntime: at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2171)
02-07 16:58:38.120 10303 7721 7721 E AndroidRuntime: at android.app.Instrumentation.execStartActivity(Instrumentation.java:1805)
02-07 16:58:38.120 10303 7721 7721 E AndroidRuntime: at android.app.Activity.startActivityForResult(Activity.java:5596)
02-07 16:58:38.120 10303 7721 7721 E AndroidRuntime: at com.microsoft.intune.mam.client.app.MAMActivity.startActivityForResultReal(Unknown Source:1)

**Comment by Archit-Pikle** [comment]
Hi @ravish2038 , we need more information to investigate this bug. Can you please fill this template out - 

## Summary

Please briefly describe the issue you are experiencing.

## Details

- **`Microsoft.Intune.Maui.Essentials.android` Version:**
- **Operating System (Mac, Linux, Windows) and Version**:
- **Visual Studio Version**:

## Logs

For **build issues**, please include:

- MSBuild Logs

For **runtime issues**, please include:

- MSBuild Logs
- CP Logs

### MSBuild Logs

**Please attach the binary log (`.binlog`) from your build.**

For guidance, see
[Obtain build logs with MSBuild](https://learn.microsoft.com/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2022), specifically
how to [Save a binary log](https://learn.microsoft.com/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2022#save-a-binary-log).

### Company Portal Logs

**PowerLift ID:**

For guidance, see
[Report a problem in Company Portal or Intune app for Android](https://learn.microsoft.com/mem/intune/user-help/send-logs-to-your-it-admin-by-email-android)

## NuGet Dependencies

If your app includes third-party NuGet libraries, please list them here:

- NA

## Questions to Ask Before Submission

1. Does the app build and launch without including the `Microsoft.Intune.Maui.Essentials.android` package?
2. Does the issue reproduce if you rebuild after deleting the `bin` and `obj` output folders?
3. Have you checked the [.NET MAUI repository](https://github.com/dotnet/maui/issues) for similar issues? If so, please follow the guidance there or add that information to this issue.
4. Are you using the latest `Microsoft.Intune.Maui.Essentials.android` NuGet package version?
