### ISSUE TITLE
Fatal Exception: com.microsoft.intune.mam.client.ipc.exceptions.AgentIpcException

### ISSUE THREAD

**Issue by singh-srikant** [msintuneappsdk/ms-intune-app-sdk-android#219]
## Summary
We are getting a crash that is observed mostly on Android 14 and Samsung devices. It is reported on Firebase crashlytics and we are unable to reproduce this issue. The crash numbers have spiked in the latest releases and have 1,212 crash events affecting 815 users in the last 7 days.

```
Fatal Exception: com.microsoft.intune.mam.client.ipc.exceptions.AgentIpcException
Android threw AgentInterruptedException. Agent flags: 0doze: false; app inactive: false; agent inactive: false; device interactive: false; power save: false; agent disabled: false; provider disabled: false; app battery bucket: 10. Method invoked: methodName: onMAMAppInstall; returnType: void
```

```
Caused by com.microsoft.intune.mam.client.ipc.exceptions.AgentInterruptedException
After calling onMAMAppInstall we received a null or empty bundle as a return. Agent could have been killed mid-transaction or the binder crashed. Agent flags: 0doze: false; app inactive: false; agent inactive: false; device interactive: false; power save: false; agent disabled: false; provider disabled: false; app battery bucket: 10
```

**Devices:** Samsung (84%), Nothing(14%)
**Operating System:** Android 14 (87%), Android 13(12%)

## Details

- **Intune Android App SDK Version: 9.1.0** 
- **gradleEnterprisePlugin: 3.5.1**
- **AGP Version: 7.4.0**
- **Android Device Make and Model: Galaxy S21 5G, Galaxy S23 Ultra, Galaxy S21 Ultra 5G**
- **Android Device OS Version: 14, 13**

## Logs
```
Fatal Exception: com.microsoft.intune.mam.client.ipc.exceptions.AgentIpcException: Android threw AgentInterruptedException. Agent flags: 0doze: false; app inactive: false; agent inactive: false; device interactive: false; power save: false; agent disabled: false; provider disabled: false; app battery bucket: 20. Method invoked: methodName: onMAMAppInstall; returnType: void
       at com.microsoft.intune.mam.client.ipc.ContentProviderEndpointProxy$EndpointProxyInvocationHandler.doAgentIpc(:203)
       at com.microsoft.intune.mam.client.ipc.ContentProviderEndpointProxy$EndpointProxyInvocationHandler.lambda$invoke$0(:115)
       at com.microsoft.intune.mam.client.ipc.ContentProviderEndpointProxy$EndpointProxyInvocationHandler.$r8$lambda$4ul3oLE8a3KiHXWtLIaVNHTwAeU()
       at com.microsoft.intune.mam.client.ipc.ContentProviderEndpointProxy$EndpointProxyInvocationHandler$$ExternalSyntheticLambda0.call(:10)
       at com.microsoft.intune.mam.client.identity.IdentityCallable.call(:38)
       at java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
```

```
Caused by com.microsoft.intune.mam.client.ipc.exceptions.AgentInterruptedException: After calling onMAMAppInstall we received a null or empty bundle as a return. Agent could have been killed mid-transaction or the binder crashed. Agent flags: 0doze: false; app inactive: false; agent inactive: false; device interactive: false; power save: false; agent disabled: false; provider disabled: false; app battery bucket: 20
       at com.microsoft.intune.mam.client.ipc.BundleMarshal.unmarshalOne(:161)
       at com.microsoft.intune.mam.client.ipc.ContentProviderEndpointProxy$EndpointProxyInvocationHandler.makeContentProviderCall(:378)
       at com.microsoft.intune.mam.client.ipc.ContentProviderEndpointProxy$EndpointProxyInvocationHandler.doAgentIpc(:175)
       at com.microsoft.intune.mam.client.ipc.ContentProviderEndpointProxy$EndpointProxyInvocationHandler.lambda$invoke$0(:115)
       at com.microsoft.intune.mam.client.ipc.ContentProviderEndpointProxy$EndpointProxyInvocationHandler.$r8$lambda$4ul3oLE8a3KiHXWtLIaVNHTwAeU()
       at com.microsoft.intune.mam.client.ipc.ContentProviderEndpointProxy$EndpointProxyInvocationHandler$$ExternalSyntheticLambda0.call(:10)
       at com.microsoft.intune.mam.client.identity.IdentityCallable.call(:38)
       at java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
```

## AndroidX Dependencies

If your app includes any AndroidX libraries, please list them here, along with the version info:

androidxCore = "1.10.1"
androidxLifecycle = "2.4.1"
androidxWorkManager = "2.8.1"
androidxNavigation = "2.5.2"
androidxStartupRuntime = "1.1.0"
androidxDatastore = "1.0.0"

## Third-Party Library Dependencies

If your app includes any third-party libraries, please list them here, along with the version info:

- NA

**Comment by mukeshk-ms** [comment]
Duplicate of #105 
@singh-srikant we are tracking this issue internally

**Comment by mukeshk-ms** [comment]
Duplicate of #105 
@singh-srikant we are tracking this issue internally
