### ISSUE TITLE
app crashes when running unregisterAccountForMAM

### ISSUE THREAD

**Issue by bjartebore** [msintuneappsdk/ms-intune-app-sdk-android#37]
**Describe the bug:**
When I unregister my account with unregisterAccountForMAM() the application crashes from what I do believe is from a background service (WorkplaceJoinManagerService). 

**To Reproduce**

* do a successful enrollement with: MAMComponents.get(MAMEnrollmentManager.class).registerAccountForMAM(...)
* run: MAMComponents.get(MAMEnrollmentManager.class).unregisterAccountForMAM("my.username@myhost.com"); 

**Expected behavior:**
I would expect the app to be unregistered.

**logs:**
2020-05-14 14:01:16.682 6589-8756/? E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    java.lang.RuntimeException: android.os.RemoteException: Unable to get WPJ device id
        at android.os.Parcel.writeException(Parcel.java:1882)
        at android.os.Binder.execTransact(Binder.java:710)
     Caused by: android.os.RemoteException: Unable to get WPJ device id
        at com.microsoft.windowsintune.companyportal.workplace.WorkplaceJoinManagerService$WPJManagerBinder.getDeviceId(WorkplaceJoinManagerService.java:90)
        at com.microsoft.intune.companyportal.workplace.IWPJManagerService$Stub.onTransact(IWPJManagerService.java:51)
        at android.os.Binder.execTransact(Binder.java:697)

**Smartphone (please complete the following information):**
 - Android emulator (API 27, 

**Intune App SDK for Android :**
- Intune 6.5.3
- Platform: Java, Flutter, Android compile SDK 28, Android targetSdk 27, minSdk 16

**Comment by bjartebore** [comment]
It seems like my issue is related to the default WIPE_USER_DATA event running after unregisterAccountForMAM, implementing the notification receiver manually seems to resolve my issue. Closing the issue
