### ISSUE TITLE
MAMJobSchedulerHelper throws IllegalArgumentException

### ISSUE THREAD

**Issue by MariusVolkhart** [msintuneappsdk/ms-intune-app-sdk-android#41]
**Describe the bug:**
When using v6.5.3 of the SDK, our app sees errors logged from the MAM SDK.

```java
E/MAMJobSchedulerHelper: Exception thrown when trying to submit an internal job.
    java.lang.IllegalArgumentException: Scheduled service ComponentInfo{com.example.myapp/com.microsoft.intune.mam.client.service.MAMBackgroundJobService} does not require android.permission.BIND_JOB_SERVICE permission
        at android.os.Parcel.createException(Parcel.java:2075)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:308)
        at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:43)
        at com.microsoft.intune.mam.client.service.MAMJobSchedulerHelper.scheduleJob(MAMJobSchedulerHelper.java:152)
        at com.microsoft.intune.mam.client.service.MAMJobSchedulerHelper.submitFileEncryptionJobIfNeeded(MAMJobSchedulerHelper.java:145)
        at com.microsoft.intune.mam.client.fileencryption.FileEncryptionServiceBehavior.schedule(FileEncryptionServiceBehavior.java:282)
        at com.microsoft.intune.mam.client.fileencryption.FileEncryptionServiceBehavior.schedule(FileEncryptionServiceBehavior.java:250)
        at com.microsoft.intune.mam.client.fileencryption.FileEncryptionManager.initialize(FileEncryptionManager.java:375)
        at com.microsoft.intune.mam.client.ipcclient.MAMClientImpl.initialize(MAMClientImpl.java:272)
        at com.microsoft.intune.mam.client.ipcclient.MAMClientSingletonImpl.ensureInitialized(MAMClientSingletonImpl.java:73)
        at com.microsoft.intune.mam.client.app.ApplicationBehaviorImpl.attachBaseContext(ApplicationBehaviorImpl.java:98)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(InterProxy.java:85)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy5.attachBaseContext(Unknown Source)
        at com.microsoft.intune.mam.client.app.MAMApplication$Impl.attachBaseContext(MAMApplication.java:92)
        at com.microsoft.intune.mam.client.app.MAMApplication.attachBaseContext(MAMApplication.java:43)
        at android.app.Application.attach(Application.java:351)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1149)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1218)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:2673)
        at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2728)
        at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:153)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
```

It is clear to me that MAM expects me to configure my `AndroidManifest.xml` to support this service, but the service is undocumented, and this expectation is undocumented. Developers should not be expected to reverse engineer SDK requirements.

**Expected behavior:**
At a minimum, I expect the docs to explain what the service is, and how to configure it. Really, the AAR should be published that has the manifest settings required, and the build tools will handle manifest merging.

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 6.5.3, yes
- What platform is your app based in?: Java
- For errors post build, does the app launch without being Intune SDK integrated? Yes

**Comment by MariusVolkhart** [comment]
We're seeing error messages coming from `MAMBackgroundService` as well. Looks like another undocumented service that needs to be exported?

**Comment by MariusVolkhart** [comment]
```xml
<service
            android:name="com.microsoft.intune.mam.client.service.MAMBackgroundJobService"
            android:exported="true"
            android:permission="android.permission.BIND_JOB_SERVICE" />
```
seems to be sufficient for the `MAMBackgroundJobService`, but we don't know the permissions required for the `MAMBackgroundService`. This `Service` seems to be used on API 23 (Android 6).

**Comment by MariusVolkhart** [comment]
We were looking only in the Core JAR and did not see the AAR. Have since found the AAR and the included `AndroidManifest`. Going to echo #40 and say that having this lib published somewhere, even on GitHub or Azure DevOps and consuming via a regular maven dependency would have saved us a lot of time.
