### ISSUE TITLE
Execution failed for task ':app:transformClassesWithMamifyTransformForDevDebug'. > java.lang.NullPointerException (no error message)

### ISSUE THREAD

**Issue by PREric** [msintuneappsdk/ms-intune-app-sdk-android#67]
URGENT!!!! 
Keep having 
```
Mamification failed: null
java.lang.NullPointerException
```

Build.gradle
```
   compileSdkVersion 29
   minSdkVersion 26
   targetSdkVersion 29
```
```

Rewriting com.microsoft.identity.client.BrowserTabActivity superclass from android.app.Activity to com.microsoft.intune.mam.client.app.MAMActivity
Mamification failed: null
java.lang.NullPointerException
	at com.microsoft.intune.mam.BuildTimeMamifier.mamifyClass(BuildTimeMamifier.java:378)
	at com.microsoft.intune.mam.BuildTimeMamifier.mamifyClasses(BuildTimeMamifier.java:190)
	at com.microsoft.intune.mam.BuildTimeMamifier.mamify(BuildTimeMamifier.java:108)
```

for transforming different classes

**Comment by meghandaly** [comment]
@PREric Can you please indicate which version of the SDK you are using and experiencing this issue with? There was a known issue whereby the build plugin could throw a NPE that was resolved in [version 7.0.1](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/releases/tag/7.0.1).
