### ISSUE TITLE
 Failed to get current file encryption key because this app is not trusted. Crash on start up.

### ISSUE THREAD

**Issue by maphongba008** [msintuneappsdk/ms-intune-app-sdk-android#70]
**Describe the bug:**

**To Reproduce**
1. Integrate Intune SDK
2. Run the app in debug mode

**Screenshots and logs:**

```

com.microsoft.intune.mam.client.fileencryption.MAMKeyRetrievalException: Failed to get current file encryption key because this app is not trusted.
        at com.microsoft.intune.mam.client.ipcclient.MAMClientImpl.getCurrentFileEncryptionKey(MAMClientImpl.java:488)
        at com.microsoft.intune.mam.client.fileencryption.FileEncryptionKeyCacheImpl.getCurrentMasterKeyId(FileEncryptionKeyCacheImpl.java:68)
        at com.microsoft.intune.mam.client.fileencryption.FileEncryptionManager.encryptData(FileEncryptionManager.java:667)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
        at libcore.io.IoBridge.open(IoBridge.java:482)
    	at java.io.FileOut
2021-05-25 12:08:01.927 16241-16289/com.leapxpert.leap.work.intune E/ntProviderEndpointProxy: Logging telemetry after IPC failure
    com.microsoft.intune.mam.client.ipc.exceptions.SignatureMismatchException: Signature mismatch for package com.leapxpert.leap.work.intune
        at com.microsoft.intune.mam.client.ipc.MAMContentProviderBase.checkSignatureForPackageIfSignatureKnown(MAMContentProviderBase.java:110)
        at com.microsoft.intune.mam.client.ipc.MAMContentProviderBase.verifyCallerIsManaged(MAMContentProviderBase.java:58)
        at com.microsoft.intune.mam.client.ipc.AbstractAppPolicyContentProvider.call(AbstractAppPolicyContentProvider.java:125)
        at android.content.ContentProvider.call(ContentProvider.java:2152)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:477)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:277)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)


```

**Smartphone (please complete the following information):**
- Emulator

**Intune App SDK for Android (please complete the following information):**
7.0.1

**Comment by maphongba008** [comment]
add signing configs for debug mode resolved the issue.
